[UI] Add tabs wrapping on Product show page > Attributes section
Sylius/Sylius pull request #11425
Opened 2020-05-06 10:49 UTC by SirDomin

| Q               | A
| --------------- | -----
| Branch?         | 1.6, 1.7 or master 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2020-05-06 10:50 UTC, Tomanhez approved these changes

2020-05-06 10:59 UTC, GSadee requested changes
As it is a bug fix, I would be for changing the branch to 1.7.

And could you add some screenshots to show how the product show page looks after the change?

2020-05-06 10:59 UTC, GSadee commented on src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
> +.ui.top.attached.tabular.menu{
```suggestion
.ui.top.attached.tabular.menu {
```

2020-05-06 11:37 UTC, kulczy commented
it would be a bit clearer to put it under the `tabs` comment rather than `menu`

2020-05-06 18:44 UTC, lchrusciel commented
We need to resolve https://github.com/Sylius/Sylius/pull/11427 to merge this PR

2020-05-07 05:58 UTC, GSadee approved these changes

2020-05-07 06:05 UTC, GSadee commented
Probably rebase should fix the build

2020-05-07 12:50 UTC, pamil approved these changes
Build will be fixed by #11430.

2020-05-07 12:50 UTC, merged

2020-05-07 12:50 UTC, pamil commented
Thank you, @SirDomin! :tada: