Add proper date on license
Sylius/Sylius pull request #12288
Opened 2021-01-29 09:06 UTC by Tomanhez

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

2021-01-29 10:38 UTC, pamil requested changes
Could you replace it in all the bundles and components?

2021-01-29 11:53 UTC, Tomanhez commented
@pamil I think that is all

2021-02-01 13:27 UTC, pamil approved these changes

2021-02-01 13:27 UTC, merged

2021-02-01 13:27 UTC, pamil commented
Thanks, Tomasz! :1st_place_medal: