[WIP] serializer added
Sylius/Sylius pull request #12392
Opened 2021-03-01 09:33 UTC by SirDomin

| Q               | A
| --------------- | -----
| Branch?         | 1.9
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2021-03-09 13:36 UTC, pamil requested changes
It's a BC break so this PR should target the master branch.

2021-03-09 13:36 UTC, pamil commented on src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
> +        return $this->responseChecker->getCollection($this->ordersClient->getLastResponse())[0];
Shouldn't `getCartShippingMethods` method return all the shipping methods data (instead of just the first one)?

2021-03-09 13:36 UTC, pamil commented on src/Sylius/Bundle/ApiBundle/Serializer/CartShippingMethodSerializer.php
> +        $data['price'] = $calculator->calculate($shipment, $shippingMethod->getConfiguration());
Are those lines actually needed? `$data` is an array not-passed by reference so it should have no effect (and the price comes from `getCartShippingMethods` in this case).

2021-03-09 13:36 UTC, pamil commented on src/Sylius/Bundle/ApiBundle/Serializer/CartShippingMethodSerializer.php
> +                'price' => $price
```suggestion
                'price' => $price,
```

2021-03-09 13:37 UTC, pamil commented
Also, we should include this change in `UPGRADE-1.10.md` file (price instead of cost, nested array of shipping methods).

2021-06-17 11:08 UTC, GSadee commented
Closing in favour of #12713

2021-06-17 11:08 UTC, closed without merging