Change default Liip loader and resolver names
Sylius/Sylius pull request #12543
Opened 2021-04-19 11:55 UTC by Zales0123

| Q               | A
| --------------- | -----
| Branch?         | 1.8
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #8143
| License         | MIT

As mentioned in [this comment](https://github.com/Sylius/Sylius/issues/8143#issuecomment-392771696), we should avoid using a `default` name for the Liip resolver and loader. Such a change would resolve in the easier bundle configuration overriding (although there is still work to be done on the Liip side).

I believe this change does not introduce any BC break (as we still use the new names of resolver/loader as the defaults one). I wonder, should it be specified in the core or in the Sylius-Standard 🤔 It would also probably deserve a mention in the `UPGRADE` file 🚀

2021-04-19 14:11 UTC, lchrusciel submitted a review, later dismissed
However, I would vote for leaving just a note in the upgrade file. Also, it seems that you were correct, Sylius-Standard should be fixed as well: https://github.com/Sylius/Sylius/pull/12543/files

2021-04-20 07:44 UTC, Zales0123 commented
`UPGRADE` file updated 👍

2021-04-20 10:15 UTC, pamil requested changes
Correct me if I'm wrong - this looks like BC break given the following scenario:

1. Install Sylius-Standard with Sylius before this change happens
2. Customise `default` loader/resolver after CoreBundle configuration is loaded, in `liip_imagine.yaml` (`_sylius.yaml` is loaded first, `liip_imagine.yaml` is loaded afterwards)
3. Since CoreBundle configuration changed the default implementation of `cache` and `data_loader` to `sylius_image`, this previous customisation of `default` ones will stop working after upgrading to Sylius with this PR included

2023-09-19 10:05 UTC, jakubtobiasz commented
I rebased the PR against the `2.0` branch :).

2023-09-19 10:06 UTC, jakubtobiasz commented on config/packages/liip_imagine.yaml
I removed this file as it seems to work without it
<img width="452" alt="CleanShot 2023-09-19 at 12 06 13@2x" src="https://github.com/Sylius/Sylius/assets/80641364/96118239-010d-422a-b83a-6c90d00159d9">

2023-09-19 10:45 UTC, Rafikooo approved these changes, later dismissed

2023-09-19 12:59 UTC, Wojdylak submitted a review, later dismissed

2023-09-21 06:26 UTC, GSadee approved these changes

2023-09-21 06:27 UTC, merged

2023-09-21 06:27 UTC, GSadee commented
Thanks, Mateusz! :1st_place_medal: