[Api] adding product from another channel
Sylius/Sylius pull request #12598
Opened 2021-05-05 08:50 UTC by arti0090

| Q               | A
| --------------- | -----
| Branch?         |  master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | continues #12579
| License         | MIT

2021-05-05 10:09 UTC, AdamKasp requested changes

2021-05-05 10:09 UTC, AdamKasp commented on features/checkout/preventing_adding_to_cart_product_or_variant_from_another_channel.feature
> +        Then I should be informed that product "Pain" is not available in current channel
```suggestion
        Then I should be informed that product "Pain" is not available
```
information about different channels shouldn't be provided to customer
now if you will add to cart a non-existent product you will get 500, so or we should have the same result here or validation message like "there is są product 'Pain' in shop'"

2021-05-05 11:06 UTC, AdamKasp approved these changes

2021-05-06 09:21 UTC, GSadee reviewed
For me, preventing adding wrong product to the cart is a bug fix, so I would be for changing the base branch to at least `1.9`

2021-05-06 09:21 UTC, GSadee commented on src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantAvailableInChannelValidator.php
> +        $productVariant = $this->productVariantRepository->findOneBy(['code' =>$value->productVariantCode]);
```suggestion
        $productVariant = $this->productVariantRepository->findOneBy(['code' => $value->productVariantCode]);
```

2021-05-06 09:21 UTC, GSadee commented on src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantAvailableInChannelValidator.php
> +        if(!$product->hasChannel($cartChannel)) {
```suggestion
        if (!$product->hasChannel($cartChannel)) {
```

2021-05-06 09:21 UTC, GSadee commented on src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantAvailableInChannelValidator.php
> +final class ProductOrVariantAvailableInChannelValidator extends ConstraintValidator
```suggestion
final class ProductAvailableInChannelValidator extends ConstraintValidator
```
?

2021-05-06 09:21 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
> +            not_available: 'There is no product %productName% in this shop.'
I would be for adding this message to the `validators.en.yaml` in `ApiBundle` as the validator is there
```suggestion
            not_available: 'The product %productName% does not exist.'
```

2021-05-07 07:07 UTC, arti0090 commented
Closing as it is now moved to 1.9 on PR #12609

2021-05-07 07:07 UTC, closed without merging