[API] Add missing inStock field to swagger
Sylius/Sylius pull request #12653
Opened 2021-05-20 06:23 UTC by arti0090

| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | no
| New feature?    | yes (missed thing)
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | Extends #12639
| License         | MIT

I forgot to add this to PR, forgive me sylius 🙏 

![Zrzut ekranu 2021-05-20 o 08 20 17](https://user-images.githubusercontent.com/35863747/118929254-8f6afc00-b944-11eb-9858-f0592a86bb5a.png)

2021-05-20 06:47 UTC, lchrusciel approved these changes
forgiveness granted

2021-05-20 06:48 UTC, GSadee requested changes
I'm almost sure, that this field has been added to ProductVariant, not Product

2021-05-20 06:48 UTC, arti0090 commented
Thats true @GSadee i am just changing it

2021-05-20 07:05 UTC, arti0090 commented
![Zrzut ekranu 2021-05-20 o 09 04 11](https://user-images.githubusercontent.com/35863747/118934174-5b92d500-b94a-11eb-8caf-d96b91396d5c.png)

Changed for ProductVariant, also fixed the missing `price` field

2021-05-20 07:20 UTC, GSadee commented on src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php
> +        $docs['components']['schemas']['ProductVariant.jsonld-admin.product_variant.read']['properties']['price'] = $priceSchema;
`price` field has been also added only for shop endpoints
```suggestion
```

2021-05-22 16:53 UTC, lchrusciel approved these changes

2021-05-24 04:37 UTC, GSadee approved these changes

2021-05-24 04:37 UTC, merged

2021-05-24 04:37 UTC, GSadee commented
Thank you, @arti0090! :tada: