[API] add original price to product variant
Sylius/Sylius pull request #12877
Opened 2021-08-10 22:02 UTC by SirDomin

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2021-08-11 05:02 UTC, arti0090 approved these changes

2021-08-11 05:02 UTC, arti0090 commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +    public function iShouldNotSeeTheProductOriginalPrice(): void
```suggestion
    public function iShouldNotSeeAnyOriginalPrice(): void
```

2021-08-11 06:03 UTC, AdamKasp requested changes

2021-08-11 06:03 UTC, AdamKasp commented on src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
> +        }
And do we really want to do it in this way? IMO JSON should always look the same way, if `originalPrice` is configured it should show this value if not it should show maybe `null`. From a frontend perspective JSON with a "random" body will cause unexpected errors (I always check the value of the field instead the existence of this field)

2021-08-11 08:49 UTC, Arminek commented on src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
> +    private $client;
Can we start using typed properties?

2021-08-11 09:46 UTC, SirDomin commented on src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
> +    private $client;
sounds good to me

2021-08-11 12:10 UTC, AdamKasp requested changes

2021-08-11 12:10 UTC, AdamKasp commented on src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
> +            $data['original_price'] = ($data['price'] === $originalPrice ? null : $originalPrice);
but if `originalPrice` is equal to `price` we should show 2 same value for `price` and `originalPrice` with this code, you will overwrite `originalPrice` :(

what if you will only leave ` data['original_price'] = $originalPrice`

2021-08-11 12:39 UTC, AdamKasp approved these changes

2021-08-11 17:59 UTC, Tomanhez approved these changes

2021-08-12 05:49 UTC, merged

2021-08-12 05:49 UTC, AdamKasp commented
Thanks, @SirDomin! :1st_place_medal:

2021-08-12 12:14 UTC, lchrusciel commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +        foreach ($products as $product) {
Why do we have an array of products here? Also, this loop just checks if there is any product with `original_price`, not the particular, which seems bad