[CatalogPromotions] Add fixtures for catalog promotions rule
Sylius/Sylius pull request #13055
Opened 2021-09-03 11:14 UTC by Tomanhez

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

2021-09-03 11:26 UTC, AdamKasp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> +                                catalogPromotion: 'winter'
you should also configure here rule configuration - array with `productVariants` codes

2021-09-03 11:26 UTC, AdamKasp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> +                                catalogPromotion: 'winter'
imo this config shoudl look like:
```suggestion
                            rule_for_variants:
                                catalogPromotion: 'winter'
                                rule: 'for_variants'
                                configuration:
                                - 'first_variant_code'
                                - 'second_variant_code'
```

WDYT about it :)?

2021-09-03 11:41 UTC, GSadee requested changes

2021-09-03 11:41 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> +                catalog_promotion_rule:
There shouldn't be a possibility to define rules (and actions) independently of the catalog promotions. It should be implemented similarly to rules for cart promotion

2021-09-03 11:41 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Fixture/CatalogPromotionRuleFixture.php
> +final class CatalogPromotionRuleFixture extends AbstractResourceFixture
IMO this fixture file is probably not needed and this configuration tree should be placed in CatalogPromotionFixture

2021-09-07 04:48 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php
> +    public function __construct(FactoryInterface $catalogPromotionActionFactory) {
```suggestion
    public function __construct(FactoryInterface $catalogPromotionActionFactory)
    {
```

2021-09-07 04:48 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> +                                            - amount: 500
As we are setting the percentage value as float:
```suggestion
                                            - amount: 0.5 
```

2021-09-08 04:50 UTC, GSadee approved these changes

2021-09-08 04:50 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php
> +            ->setDefault('configuration', [])
I would be for setting some amount as a default configuration because now, the default action in invalid

2021-09-08 04:50 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionRuleExampleFactory.php
> +            ->setDefault('configuration', [])
Similar as above

2021-09-08 04:50 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> +                                            - amount: 0.5
```suggestion
                                            amount: 0.5
```

2021-09-08 04:51 UTC, merged

2021-09-08 04:51 UTC, GSadee commented
Thank you, Tomasz! :tada: