BUGFIX: Sylius#11975 Added check for existing admin user id before…
Sylius/Sylius pull request #13241
Opened 2021-10-22 12:44 UTC by alex-boehm

… rendering Avatar delete button

| Q               | A
| --------------- | -----
| Branch?         | 1.9
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11975
| License         | MIT

2022-01-03 18:20 UTC, vvasiloi commented
Hey @alex-boehm, thank you for your contribution!
Can you explain the reason behind this change? Why would it be necessary?

2022-01-03 18:40 UTC, alex-boehm commented
Hi @vvasiloi,
the corresponding bug is https://github.com/Sylius/Sylius/issues/11975.

How to reproduce the issue:
1. Go to Administrator Section in Backend
2. Start to create a new Administrator
3. !! Only add an image to the administrator, leave all other (required) fields empty
4. Save

Result:
CSRF Token error.

Reason:
The code for rendering the Delete-Button for the avatar image requires the record-Id to build the link ('id': app.request.attributes.get('id')) .
In this case we don't have an existing record because we left all other fields empty, BUT we have an avatar image, so the check " admin_user.avatar is not null" is true here and building the link for the delete button fails.

2022-01-03 19:18 UTC, vvasiloi requested changes
Thank your! I'm sorry, I didn't notice it references an issue.
I believe this is supposed to work only on the edit page.
Considering that, I suggested a small improvement.

2022-01-03 19:18 UTC, vvasiloi commented on src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
>                  <button formaction="{{ path('sylius_admin_admin_user_remove_avatar', {'id': app.request.attributes.get('id'), '_csrf_token': csrf_token(app.request.attributes.get('id'))}) }}" type="s
```suggestion
            {% if admin_user.id is not null and admin_user.avatar is not null %}
                <button formaction="{{ path('sylius_admin_admin_user_remove_avatar', {'id': admin_user.id, '_csrf_token': csrf_token(admin_user.id)}) }}" type="submit" class="ui icon red labeled button">
```

2022-01-03 19:20 UTC, vvasiloi commented
Also, please rebase you branch an change the PR base branch to 1.10.

2023-07-09 08:29 UTC, jakubtobiasz commented
Closing as this PR has been replaced by #15148. Of course, @alex-boehm you're added as a co-author of the new commit :).

2023-07-09 08:29 UTC, closed without merging