[CartPromotion][API][UI] Apply on discounted flag added to cart promotion
Sylius/Sylius pull request #13328
Opened 2021-11-24 12:41 UTC by AdamKasp

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| License         | MIT

2021-11-25 10:01 UTC, SirDomin approved these changes

2021-11-25 10:04 UTC, lchrusciel commented on src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
> +    }
Can we put it next to the others whens?

2021-11-25 10:04 UTC, lchrusciel commented on tests/Api/Responses/Expected/admin/post_promotion_response.json
> +    "createdAt": @string@,
```suggestion
    "createdAt": @string@.isDateTime(),
```

2021-12-01 10:20 UTC, GSadee commented on src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
> +                <option name="default">0</option>
Shouldn't the default value be true as it is the current behaviour?

2021-12-01 10:20 UTC, GSadee commented on src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
> +        <field name="applyOnDiscounted" column="apply_on_discounted" type="boolean">
```suggestion
        <field name="applicableToDiscounted" column="applicable_to_discounted" type="boolean">
```
?

2021-12-01 11:30 UTC, AdamKasp commented on tests/Api/Responses/Expected/admin/post_promotion_response.json
> +    "updatedAt": @string@
it doesn't work in this way, the checker see it as a string `@string@.isDateTime()`

2021-12-01 12:18 UTC, GSadee commented on src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
> +        <field name="applicableOnDiscounted" column="applicable_on_discounted" type="boolean">
```suggestion
        <field name="applicableToDiscounted" column="applicable_to_discounted" type="boolean">
```

2021-12-01 12:18 UTC, GSadee commented on features/promotion/managing_promotions/adding_promotion.feature
> +        And the "Full metal promotion" promotion should not be applicable on discounted items
```suggestion
        And the "Full metal promotion" promotion should not be applicable to discounted items
```

2021-12-01 13:59 UTC, CoderMaggie requested changes

2021-12-01 13:59 UTC, CoderMaggie commented on src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
> +            applicable_to_discounted: Applicable to discounted
```suggestion
            applies_to_discounted: Applies to already discounted order items
```

2021-12-01 13:59 UTC, CoderMaggie commented on src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
> +            applicable_to_discounted_details: With this option cart promotion will apply to product discounted by catalog promotion.
```suggestion
            applies_to_discounted_details: With this option the cart promotion will be applied to order items already discounted by catalog promotion(s).
```

2021-12-02 12:20 UTC, GSadee approved these changes

2021-12-02 12:21 UTC, merged

2021-12-02 12:21 UTC, GSadee commented
Thanks, Adam! :1st_place_medal: