AdminBundle - Flag review on product details
Sylius/Sylius pull request #13334
Opened 2021-11-25 17:28 UTC by adpeyre

| Q               | A
| --------------- | -----
| Branch?         | 1.10 or master 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2022-01-03 16:47 UTC, vvasiloi requested changes, later dismissed
Hey @adpeyre, thank you for your contribution.
I wonder if I missed it in [Flags are not languages](https://github.com/Sylius/Sylius/pull/10553), or if it was added later.
Anyway, I suggested a small change that will simplify things.

2022-01-03 16:47 UTC, vvasiloi commented on src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_moreDetails.html.twig
> +            {{ flags.fromCountryCode(translation.locale|sylius_locale_country|lower) }}
There's a  `fromLocaleCode` macro that returns the flag based on locale code, if possible.

```suggestion
            {{ flags.fromLocaleCode(translation.locale) }}
```

2023-08-11 12:18 UTC, NoResponseMate approved these changes

2023-08-14 07:20 UTC, jakubtobiasz approved these changes

2023-08-14 07:21 UTC, merged

2023-08-14 07:21 UTC, jakubtobiasz commented
Thank you, @adpeyre!