[Docs] Catalog promotion label customization
Sylius/Sylius pull request #13386
Opened 2021-12-14 07:49 UTC by AdamKasp

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| License         | MIT

2021-12-14 08:02 UTC, Zales0123 reviewed
If we need to override so much code just to customize the label... it seems that something is wrong :( Maybe we can extract some template and make it simpler and more generic?

2021-12-14 22:43 UTC, CoderMaggie requested changes
Let's maybe rename the file to be simply:
`docs/cookbook/promotions/catalog-promotion-labels.rst`

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +--------------------------------------------
```suggestion
Change the catalog promotion labels' styles
-------------------------------------------
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +In default Sylius we show catalog promotion labels in 2 places: on product index and product show page. So we need to customize  2 related templates:
```suggestion
By default Sylius displays catalog promotion labels in two locations: on the products' index on product's card and also on the product show page. That's why you'll need to customize two related templates:
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +For product index, we will customize template `@SyliusShopBundle/Product/Box/_content.html.twig`
```suggestion
For product index, we will customize the ``@SyliusShopBundle/Product/Box/_content.html.twig`` template
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +by creating a file ``templates/bundles/SyliusShopBundle/Product/Box/_content.html.twig`` with content:
```suggestion
by overriding it with your own ``templates/bundles/SyliusShopBundle/Product/Box/_content.html.twig`` that will have such content:
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +by creating a file ``templates/bundles/SyliusShopBundle/Product/Show/_price.html.twig`` with content:
```suggestion
For product show page you'll need to override the ``@SyliusShopBundle/Product/Show/_price.html.twig`` template with ``templates/bundles/SyliusShopBundle/Product/Show/_price.html.twig`` looking like that:
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +
```suggestion

Of course, you can modify the styles how you need, also in your stylesheet.
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +Display catalog promotion labels on photo instead of under it
```suggestion
Display catalog promotion labels on the product image
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +For changing place of catalog promotion label on product index, we need to overwrite 2 templates:
```suggestion
In order to change the location of catalog promotion label on the product's card, we need to overwrite two templates. We will remove the label from underneath the photo in product card template and then add it on the product's image.
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +by creating a file ``templates/bundles/SyliusShopBundle/Product/Box/_content.html.twig`` with content:
```suggestion
Override the ``@SyliusShopBundle/Product/Box/_content.html.twig`` template with
``templates/bundles/SyliusShopBundle/Product/Box/_content.html.twig``:
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +And template `@SyliusShopBundle/Product/_mainImage.html.twig` by creating a file ``templates/bundles/SyliusShopBundle/Product/_mainImage.html.twig`` with content:
```suggestion
And the ``@SyliusShopBundle/Product/_mainImage.html.twig`` with ``templates/bundles/SyliusShopBundle/Product/_mainImage.html.twig``:
```

2021-12-14 22:43 UTC, CoderMaggie commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +    :align: center
```suggestion
    :align: center
    
    Well done! Now you can do anything you want with the catalog promotion labels.
```

🎉

2021-12-15 10:37 UTC, GSadee approved these changes

2021-12-15 10:37 UTC, GSadee commented on docs/cookbook/promotions/customize-catalog-promotion-labels.rst
> +To customize catalog promotion labels only what need to do is a overwrite proper template
```suggestion
To customize catalog promotion labels only what need to do is overwrite the proper template
```

2021-12-15 12:38 UTC, CoderMaggie commented on docs/cookbook/promotions/catalog-promotion-labels.rst
> +To customize catalog promotion labels only what need to do is overwrite the proper template
```suggestion
To customize catalog promotion labels only what need to do is overwrite their template.
```

2021-12-15 12:38 UTC, CoderMaggie commented on docs/cookbook/promotions/catalog-promotion-labels.rst
> +After changes:
```suggestion
How will it look after changes?
```

2021-12-15 12:38 UTC, CoderMaggie commented on docs/cookbook/promotions/catalog-promotion-labels.rst
> +Product details page:
```suggestion
Product show:
```

2021-12-15 12:38 UTC, CoderMaggie approved these changes

2021-12-16 10:30 UTC, GSadee approved these changes

2021-12-16 10:31 UTC, GSadee commented
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "catalog-promotion-label-customization"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

2021-12-16 10:36 UTC, merged

2021-12-16 10:36 UTC, GSadee commented
Thanks, Adam! :tada: