[Docs] How to customize the invoice logo - updated cookbook
Sylius/Sylius pull request #13421
Opened 2021-12-26 16:29 UTC by Rafikooo

| Q               | A
| --------------- | -----
| Branch?         | 1.11 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| Related tickets | https://github.com/Sylius/InvoicingPlugin/issues/254
| License         | MIT

2021-12-27 17:39 UTC, lchrusciel approved these changes

2021-12-29 21:17 UTC, CoderMaggie approved these changes

2021-12-29 21:17 UTC, CoderMaggie commented on docs/cookbook/payments/custom-invoice.rst
> +----------------------------------------
```suggestion
How to change the logo in the Invoice?
--------------------------------------
```

2021-12-29 21:17 UTC, CoderMaggie commented on docs/cookbook/payments/custom-invoice.rst
> +In order to change the logo on the invoice, set up ``SYLIUS_INVOICING_LOGO_FILE`` environment variable.
```suggestion
In order to change the logo on the invoice, set up the ``SYLIUS_INVOICING_LOGO_FILE`` environment variable.
```

2021-12-29 21:17 UTC, CoderMaggie commented on docs/cookbook/payments/custom-invoice.rst
> +If you have a privileges issue, you may also need update ``config/packages/knp_snappy.yaml`` configuration file as well:
```suggestion
If you have a privileges issue, you may also need to update the ``config/packages/knp_snappy.yaml`` configuration file as well:
```

2022-01-03 11:29 UTC, AdamKasp approved these changes

2022-01-04 10:42 UTC, GSadee commented
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "docs-cookbook-payments-custom-invoice-logo"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

2022-01-04 10:52 UTC, GSadee requested changes

2022-01-04 10:52 UTC, GSadee commented on docs/cookbook/payments/custom-invoice.rst
> +    SYLIUS_INVOICING_LOGO_FILE=/Users/sylius/logo_directory/your_custom_logo.png
You should put a custom logo in the project directory and then use it with the proper path, so as to fix the problem from issue: https://github.com/Sylius/InvoicingPlugin/issues/254

2022-01-17 06:56 UTC, GSadee commented on docs/cookbook/payments/custom-invoice.rst
> +If you have a permission issue when generating an invoice, you may also need to update the ``config/packages/knp_snappy.yaml`` configuration file.
Could you give an example with what should be set?

2022-01-17 07:41 UTC, GSadee commented on docs/cookbook/payments/custom-invoice.rst
> +            allow: 'path-to-the-logo-directory'
```suggestion
    knp_snappy:
        pdf:
            options:
                allow: %kernel.project_dir%/assets/custom-logo.png
```

2022-01-17 13:47 UTC, GSadee approved these changes

2022-01-17 13:49 UTC, merged

2022-01-17 13:49 UTC, GSadee commented
Thank you, Rafał! :1st_place_medal: