Update SalesDataProvider.php
Sylius/Sylius pull request #13432
Opened 2021-12-31 19:28 UTC by remoteclient

This would fix https://github.com/Sylius/Sylius/issues/12049

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| Related tickets | fixes #12049
| License         | MIT

The sales provider uses non standard sql code. On postgresql systems the admin area is not working. The changes makes the admin area work.

2022-01-03 14:51 UTC, vvasiloi requested changes
@remoteclient thank you for your contribution.
While this solves the problem with Postgres, it creates another one for MySQL.
Please see the failing tests and try make it green again.

2022-02-07 16:40 UTC, remoteclient commented
Hile this commit seems to work with MySQL, it fails on Postgresql again with:
```
An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 222 near 'YEAR(o.checkoutCompletedAt),': Error: Cannot group by undefined identification or result variable.").
```
Problem in the original file is, that it uses non-standard sql.

In standard sql HAVING is evaluated before SELECT, so the alias is not known to the HAVING clause.

2022-02-07 16:47 UTC, vvasiloi commented
How about using an alias in group by, but not in having?

2022-02-07 17:51 UTC, remoteclient commented
> How about using an alias in group by, but not in having?

As you can see here: [mysql having](https://www.mysqltutorial.org/mysql-having.aspx), in standard sql GROUP BY is evaluated before HAVING.

2022-02-11 17:31 UTC, remoteclient commented
Please check the results of total. I replaced the HAVING clause by WHERE

I don't believe it makes sense to use HAVING here because:

>WHERE clause introduces a condition on individual rows; HAVING clause introduces a condition on aggregations, i.e. results of selection where a single result, such as count, average, min, max, or sum, has been produced from multiple rows.

Your HAVING is not using aggregate functions, it uses MONTH, YEAR...

2022-02-11 17:37 UTC, vvasiloi commented
Indeed, it make more sense to first filter out the order that are outside the specified time range, then group them by the time unit.
I'm curious how it reflects on the performance.

2022-03-10 12:52 UTC, flolivaud commented
Hey, is it possible to move forward about this pull requests?

2022-03-10 12:54 UTC, vvasiloi approved these changes

2022-03-10 12:56 UTC, vvasiloi commented
I would love to see a performance comparison, but nevertheless this will fix the bug. Thank you, @remoteclient!

2022-03-11 08:23 UTC, remoteclient commented
@vvasiloi You are welcome! I am happy that I could contribute.

2022-03-11 08:47 UTC, GSadee approved these changes

2022-03-11 08:49 UTC, merged

2022-03-11 08:49 UTC, GSadee commented
Thank you, @remoteclient! :tada: