[Docs] add info about hardcoded translations
Sylius/Sylius pull request #13472
Opened 2022-01-12 09:02 UTC by SirDomin

| Q               | A
| --------------- | -----
| Branch?         | 1.11
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

Inform about hardcoded keys in catalog promotion scopes/actions translations

2022-01-12 13:18 UTC, CoderMaggie requested changes

2022-01-12 13:18 UTC, CoderMaggie commented on docs/cookbook/promotions/custom-catalog-promotion-action.rst
> +- fixed_discount
```suggestion
Translations for catalog promotion actions are hardcoded with such keys ``sylius.form.catalog_promotion.action.type``;
where ``type`` is one of the available catalog promotion actions: ``percentage_discount`` or ``fixed_discount``.
```

2022-01-12 13:18 UTC, CoderMaggie commented on docs/cookbook/promotions/custom-catalog-promotion-scope.rst
> +- for_variants
```suggestion
Translations for catalog promotion scopes are hardcoded with such keys ``sylius.form.catalog_promotion.scope.type``;
where ``type`` is one of the available catalog promotion actions: ``for_taxons``, ``for_products`` or ``for_variants``.
```

2022-01-12 13:52 UTC, GSadee commented on docs/cookbook/promotions/custom-catalog-promotion-action.rst
> +
Move this info to `note` block and the content to sth like that:

```suggestion
.. note::

    There is a need to define translation key in the proper format for every catalog promotion action as they are used in form types 
    to properly display different actions: ``sylius.form.catalog_promotion.action.TYPE`` where ``TYPE`` is the catalog promotion action type.

```

2022-01-13 13:09 UTC, lchrusciel approved these changes
Thats sentence is quite long, so I would recommend split it into at least two. But I don't have strong need for it

2022-01-13 13:09 UTC, lchrusciel commented on docs/cookbook/promotions/custom-catalog-promotion-action.rst
> +    to properly display different actions: ``sylius.form.catalog_promotion.action.TYPE`` where ``TYPE`` is the catalog promotion action type.
```suggestion
    to properly display different actions. The required type is: ``sylius.form.catalog_promotion.action.TYPE`` where ``TYPE`` is the catalog promotion action type.
```

2022-01-13 21:16 UTC, CoderMaggie approved these changes

2022-01-14 08:13 UTC, Zales0123 approved these changes

2022-01-14 08:13 UTC, merged