[WIP] Calendar class extraction
Sylius/Sylius pull request #13533
Opened 2022-01-25 09:09 UTC by TheMilek

| Q               | A
| --------------- | -----
| Branch?         | 1.11 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| License         | MIT

In order to unify the usage of the same method, we decided to create a separate library to avoid creating services that are based on the same functionality and use one to many instead

2022-01-25 09:25 UTC, Zales0123 commented on composer.json
> +    ],
`sylius/calendar` repository is [already on Packagist](https://packagist.org/packages/sylius/calendar), so we should be able to use it without using a custom repository setting. What we definitely should do is release a 0.1 version of it to not use `dev-master` branch 🖖

2022-01-25 09:25 UTC, Zales0123 commented on composer.json
> +        "sylius/calendar": "dev-configure-behat-step-with-calendar"
See above. It should also be sorted alphabetically

2022-01-25 09:25 UTC, Zales0123 commented on src/Sylius/Behat/Service/Provider/Calendar.php
>  final class Calendar implements DateTimeProvider, DateTimeProviderInterface
The idea of extracting this component was partially to get rid of this class 😄 so we should remove it as it's not necessary anymore, we can use [FakeCalendar](https://github.com/Sylius/Calendar/blob/master/tests/Behat/Provider/FakeCalendar.php) class from the new component

2022-01-25 09:26 UTC, Roshyo commented
This is a big BC break as some application may rely on this class.
Also since the service changed 

```diff
-        <service id="Sylius\Component\Promotion\Provider\DateTimeProviderInterface" class="Sylius\Component\Promotion\Provider\Calendar" />
+        <service id="Sylius\Calendar\Provider\DateTimeProviderInterface" class="Sylius\Behat\Service\Provider\Calendar" />
```

2022-01-25 09:36 UTC, AdamKasp requested changes

2022-01-25 09:36 UTC, AdamKasp commented on src/Sylius/Behat/Resources/config/services.xml
> +            id="Sylius\Calendar\Provider\DateTimeProviderInterface"
you should remove these configs and use service from `sylius/calendar`

2022-01-25 09:36 UTC, AdamKasp commented on src/Sylius/Behat/Service/Provider/Calendar.php
>  final class Calendar implements DateTimeProvider, DateTimeProviderInterface
this service shoud be removed and replaced by `fakeDateProvider` from `sylius/calendar`

2022-01-25 09:36 UTC, AdamKasp commented on src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
> +        <service id="Sylius\Calendar\Provider\DateTimeProviderInterface" class="Sylius\Behat\Service\Provider\Calendar" />
this service should be replaced by `Sylius\Calendar\Provider\CalendarInterface` from `sylius/calendar`

2022-01-25 09:41 UTC, AdamKasp commented
@Roshyo If I see correctly this service was added after `1.10` was released so it isn't BC break :)

2022-01-25 09:49 UTC, Zales0123 commented on composer.json
> +    ],
Should not be needed, as `sylius/calendar` is already on Packagist

2022-01-25 11:46 UTC, Roshyo commented
@AdamKasp This service exists in 1.10.0, so it means that 1.11.0 will break with it, or am I mistaken ?

2022-01-25 12:47 UTC, Zales0123 commented
@Roshyo as far as I see and remember `Sylius\Component\Promotion\Provider\DateTimeProviderInterface` does **not** exist in `1.10` (looking at [this file](https://github.com/Sylius/Sylius/blob/1.10/src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml)) 💃 so it can be safely renamed. Usage of this component in Shipment instead of [the Calendar from ShippingBundle](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShippingBundle/Provider/Calendar.php) would need proper BC layer 🖖

2022-01-27 15:40 UTC, Zales0123 commented on composer.json
> +        "sylius/calendar": "v0.1.0",
I believe it should be `^0.1` here and everywhere else

2022-01-28 06:35 UTC, GSadee commented
Closing in favour of #13557

2022-01-28 06:35 UTC, closed without merging