Fixtures/taxon factory
Sylius/Sylius pull request #13609
Opened 2022-02-07 15:05 UTC by loic425

| Q               | A
| --------------- | -----
| Branch?         | foundry-fixtures
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

2022-02-16 06:01 UTC, Roshyo approved these changes

2022-02-21 12:06 UTC, vvasiloi requested changes
It should also have `withSlug`.

2022-02-21 12:09 UTC, vvasiloi commented
I have more feedback, but it's about the logic that is being migrated, so it's better to address that later.
Let's first do the migration of current logic, then work on improving it.

2022-02-23 22:01 UTC, vvasiloi approved these changes

2022-02-23 22:04 UTC, vvasiloi approved these changes

2022-02-23 22:04 UTC, vvasiloi commented on tests/DataFixtures/Factory/TaxonFactoryTest.php
> +    function it_creates_taxon_with_descriptions_for_each_locales(): void
```suggestion
    function it_creates_taxon_with_description_for_each_locale(): void
```

2022-02-23 22:04 UTC, vvasiloi commented on tests/DataFixtures/Factory/TaxonFactoryTest.php
> +    function it_creates_taxon_with_slugs_for_each_locales(): void
```suggestion
    function it_creates_taxon_with_slug_for_each_locale(): void
```

2022-02-23 22:04 UTC, vvasiloi commented on tests/DataFixtures/Factory/TaxonFactoryTest.php
> +    function it_creates_taxon_with_names_for_each_locales(): void
```suggestion
    function it_creates_taxon_with_name_for_each_locale(): void
```

2022-02-24 14:28 UTC, vvasiloi approved these changes

2022-02-24 14:29 UTC, merged