[Fixtures] Zone factory
Sylius/Sylius pull request #13612
Opened 2022-02-08 10:39 UTC by loic425

| Q               | A
| --------------- | -----
| Branch?         | foundry-fixtures
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2022-02-21 14:49 UTC, vvasiloi requested changes
Zone factory is missing methods to set `name` and completely missing `scope` handling. 
Also, I don't think zone member factory is needed, since zone members should only be managed as part of a zone.

2022-02-22 16:30 UTC, loic425 commented on src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneFactory.php
> +    public function withMembers(array $members, ?string $type = null): self
done

2022-02-23 10:45 UTC, loic425 commented on src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneFactory.php
> +        }
```suggestion
        $data = [];

        foreach ($members as $member) {
            if (\is_string($member)) {
                $member = ZoneMemberFactory::createOne(['code' => $member]);
            }

            $data[] = $member;
        }
```

2022-02-23 10:55 UTC, vvasiloi approved these changes

2022-02-23 11:22 UTC, Roshyo approved these changes

2022-02-23 11:37 UTC, merged