Fix typo in sylius_order state machine callback
Sylius/Sylius pull request #13689
Opened 2022-02-23 11:48 UTC by vvasiloi

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13688, replaces #12762 and #12286
| License         | MIT

2022-02-23 11:53 UTC, stloyd approved these changes

2022-03-03 05:29 UTC, GSadee reviewed
It is a potential BC break IMO, so this comment is probably still valid: https://github.com/Sylius/Sylius/pull/10704#issuecomment-540441237 but wdyt @Zales0123 @lchrusciel?

2022-03-03 07:38 UTC, vvasiloi commented
> It is a potential BC break IMO, so this comment is probably still valid: [#10704 (comment)](https://github.com/Sylius/Sylius/pull/10704#issuecomment-540441237) but wdyt @Zales0123 @lchrusciel?

This is not covered by the BC promise, but I can provide a compatibility layer nonetheless, so if it is overridden with the current name it will still work as expected, but also trigger a deprecation.

2022-03-03 13:11 UTC, vvasiloi commented
Easier said than done... I didn't find a precedent for this, so I came up with this idea of writing a compiler pass that will alter the parameter that stores the state machine configuration as a BC layer. Let me know what you think.

2022-03-04 07:46 UTC, loic425 approved these changes

2022-03-04 07:47 UTC, loic425 requested changes, later dismissed
@vvasiloi A PHPUnit test for this compiler pass is missing.

2022-03-04 18:34 UTC, vvasiloi commented
@GSadee I added the BC layer.
@loic425 I added the tests for the pass.

2022-03-10 06:16 UTC, Roshyo approved these changes

2022-09-27 19:25 UTC, Rafikooo commented
Hi Folks! Yes, this typo hurts the eye, however, the problematic of the change due to the BC policy is too big compared to the benefit of no typo, so we decided to abandon this topic until the release of Sylius 2.0 💃

2022-09-28 07:44 UTC, vvasiloi commented
I made it BC, even though it's not covered by the BC promise. What's wrong with it?

2022-12-09 13:56 UTC, Rafikooo commented
After more reports from the community, we decided to reconsider this PR again :)

2023-01-03 14:00 UTC, GSadee commented on composer.json
> +        "winzou/state-machine-bundle": "~0.5"
Why?

2023-01-03 14:20 UTC, GSadee approved these changes

2023-01-03 14:20 UTC, merged

2023-01-03 14:21 UTC, GSadee commented
Thank you, Victor! :tada:

2023-01-03 14:41 UTC, Rafikooo commented on composer.json
> +        "winzou/state-machine-bundle": "~0.5"
Necessary to unlock upgrades for the rest of the affected dependencies