[Docs] Deployment on artifakt
Sylius/Sylius pull request #13723
Opened 2022-03-03 12:20 UTC by AdamKasp

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | no
| New feature?    | yes

2022-03-03 12:49 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +Artifakt is an all-in-one platform helping enterprises and developers fast-track deployments,
Could you add a link to Artifakt's website here?

```suggestion
`Artifakt <https://www.artifakt.com/>`_ is an all-in-one platform helping enterprises and developers fast-track deployments,
```

2022-03-03 12:49 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +In the second step, select the Sylius runtime and version that corresponds to the application you want to deploy. Also choose the `region <https://docs.artifakt.com/platform/available-regions>`_ wher
```suggestion
In the second step, select the Sylius runtime and version that corresponds to the application you want to deploy.
Also, choose the `region <https://docs.artifakt.com/platform/available-regions>`_ where your application and data will be deployed.
```

2022-03-03 13:35 UTC, lchrusciel commented on docs/cookbook/deployment/artifakt.rst
> +How to deploy Sylius to Artifact.com
```suggestion
How to deploy Sylius to Artifakt.com
```

2022-03-03 13:35 UTC, lchrusciel commented on docs/cookbook/deployment/artifakt.rst
> +To get off to a good start with Artifakt, you first need to create a project.
Shouldn't we mention about account creation at this stage

2022-03-07 13:27 UTC, CoderMaggie requested changes

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +    If you don't have account on **Artifakt.com**, you should request a demo or contact support first.
Could you move it under point `3.`?

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +----------------------------------
```suggestion
4. Create an environment
------------------------
```

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +----------------------------
```suggestion
3. Create an Artifakt project
-----------------------------
```

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +---------------
```suggestion
2. How does Artifakt work?
--------------------------
```

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +-------------------
```suggestion
1. What is Artifakt?
--------------------
```

2022-03-07 13:27 UTC, CoderMaggie commented on docs/cookbook/deployment/artifakt.rst
> +----------------------------------
```suggestion
5. Build the environment
------------------------
```

2022-03-09 06:50 UTC, GSadee approved these changes

2022-03-10 13:24 UTC, merged

2022-03-10 13:24 UTC, GSadee commented
Thanks, Adam! :tada: