[SymfonyTranslator] Decorate theme bundle translator to avoid memory …
Sylius/Sylius pull request #13743
Opened 2022-03-09 09:41 UTC by SirDomin

…overloading

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | MIT

2022-03-09 10:02 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +/** @inner */
```suggestion
/** @internal */
```
according to https://docs.sylius.com/en/1.9/book/organization/backward-compatibility-promise.html#code-covered

2022-03-09 10:55 UTC, AdamKasp commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +
```suggestion
```

2022-03-09 10:55 UTC, AdamKasp commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +
missing doc block

2022-03-09 10:55 UTC, AdamKasp commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +
```suggestion
```

2022-03-09 10:56 UTC, Ferror requested changes

2022-03-09 10:56 UTC, Ferror commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +    private function initialize(): void
@SirDomin the phpdoc would be the thing you would like to put in the Description. Second, there is no fix ;p The SymfonyTranslatorResourceProvider is 1to1 with the ThemeBundle one.

2022-03-09 11:21 UTC, stloyd commented on src/Sylius/Bundle/CoreBundle/Provider/SymfonyTranslatorResourceProvider.php
> +        $this->resources = [];
What about adding if+return when both variable has some content? Cause still looping over & over is not very efficient

2023-08-22 18:20 UTC, closed without merging

2023-08-22 18:20 UTC, jakubtobiasz commented
Our CI is working, so I guess this PR is obsolete.