[Product] Render disabled main taxon without link in breadcrumb
Sylius/Sylius pull request #13874
Opened 2022-04-14 11:41 UTC by hbsfaria

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13713 
| License         | MIT

When a product's main taxon is disabled, the product page breadcrumb renders it as a link and throws a Not Found exception if it is clicked.
As suggested in #13713, with this PR the breadcrumb will render the main taxon without a link (as a simple `<div>`) when the taxon is disabled.

2022-04-25 10:43 UTC, ernestWarwas requested changes
Hi @hbsfaria thank you very much for the PR it's nice 💃 . Could you provide a behat test for that?

2022-05-07 12:26 UTC, hbsfaria commented
Hi @ernestWarwas, I added a behat test ✔️

2022-05-27 10:12 UTC, ernestWarwas approved these changes

2022-06-30 10:07 UTC, GSadee approved these changes

2022-07-01 05:17 UTC, AdamKasp approved these changes

2022-07-01 05:20 UTC, merged

2022-07-01 05:20 UTC, AdamKasp commented
Thanks, @hbsfaria! :1st_place_medal: