[DOCS] Add docs about deploy platforms
Sylius/Sylius pull request #14023
Opened 2022-05-28 09:18 UTC by arti0090

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.10 |
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no/yes                                                       |
| License         | MIT                                                          |

Created unordered list of files as in tip it otherwise does not break lines between links
![image](https://user-images.githubusercontent.com/35863747/170819163-aa8a84f7-a8e2-460e-9400-9161a5f4021b.png)

2022-05-30 06:36 UTC, CoderMaggie approved these changes

2022-05-30 06:37 UTC, CoderMaggie requested changes

2022-05-30 06:37 UTC, CoderMaggie commented on docs/getting-started-with-sylius/deployment.rst
> +    - 👉 `How to deploy on Platform.sh? <https://docs.platform.sh>`_
```suggestion
    - 👉 `How to deploy on Platform.sh? <https://docs.platform.sh>`_
```

2022-05-30 08:04 UTC, CoderMaggie requested changes

2022-05-30 08:04 UTC, CoderMaggie commented on docs/getting-started-with-sylius/deployment.rst
> +    - 👉 `How to deploy on Cloudways PHP Hosting? <https://support.cloudways.com/en/>`_
```suggestion
    - 👉 :doc:`</cookbook/deployment/platform-sh>`
    - 👉 :doc:`</cookbook/deployment/cloudways>`
    - 👉 :doc:`</cookbook/deployment/symfonycloud>`
    - 👉 :doc:`</cookbook/deployment/artifakt>`
```

2022-05-30 09:36 UTC, arti0090 commented
🎉 
![image](https://user-images.githubusercontent.com/35863747/170963900-63a72b98-892d-485c-95f0-7fbebcf375d6.png)

2022-05-30 10:24 UTC, CoderMaggie approved these changes

2022-05-30 10:24 UTC, CoderMaggie commented on docs/getting-started-with-sylius/deployment.rst
> +    - `Cloudways PHP Hosting <https://support.cloudways.com/en/>`_
```suggestion
- `Platform.sh <https://docs.platform.sh>`_
- `Symfony Cloud <https://symfony.com/cloud/>`_
- `Artifakt.com <https://docs.artifakt.com/>`_
- `Cloudways PHP Hosting <https://support.cloudways.com/en/>`_
```

2022-06-13 10:03 UTC, lchrusciel approved these changes

2022-06-13 10:03 UTC, merged