[DOCS] Add note about min node version
Sylius/Sylius pull request #14246
Opened 2022-08-21 08:37 UTC by arti0090

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11              |
| License         | MIT                                                          |

It should help this issue https://github.com/Sylius/Sylius/issues/12641

2022-08-24 06:52 UTC, CoderMaggie approved these changes
@jakubtobiasz do you confirm the version?

2022-08-24 07:01 UTC, jakubtobiasz requested changes

2022-08-24 07:01 UTC, jakubtobiasz commented on docs/book/installation/requirements.rst
> +| Node.js       | 14.0+                 |
As version `16.x` doesn't work (from what I remember) writing the required version as `14.0+` may suggest everything above 14 is working (v16 including), so I suggest writing it as below:
```suggestion
| Node.js       | 14.x                 |
```

2022-10-10 07:57 UTC, CoderMaggie approved these changes

2022-10-10 08:47 UTC, GSadee approved these changes

2022-10-10 08:47 UTC, merged

2022-10-10 08:47 UTC, GSadee commented
Thanks, @arti0090! :1st_place_medal: