remove param method request
Sylius/Sylius pull request #14512
Opened 2022-11-03 06:06 UTC by everwhatever

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13  |
| Bug fix?        | yes  |
| New feature?    | no |
| BC breaks?      | no |
| Deprecations?   |no |
| Related tickets | [jira ](https://sylius.atlassian.net/browse/SYL-2349) |
| License         | MIT |

2022-11-03 09:17 UTC, GSadee requested changes
It seems like sth that does not resolve the initial problem from the issue: https://github.com/Sylius/Sylius/issues/14308.  You should definitely start from the scenario that reproduces the problem and then fix it properly.

2022-11-03 09:17 UTC, GSadee commented on src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
> -                            includeAllDescendants: "expr:parameter('sylius_shop.product_grid.include_all_descendants')"
At first glance, it should not be removed, we want to have this parameter set here.

2022-11-03 09:18 UTC, GSadee commented
And as it is a bug fix, it should be opened to 1.11 branch 😃

2023-02-24 07:05 UTC, everwhatever commented
changes are already on 1.12 branch

2023-02-24 07:05 UTC, closed without merging