[Fix][Shop] Conditional adding of logout listener
Sylius/Sylius pull request #14625
Opened 2022-12-08 14:39 UTC by NoResponseMate

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #14622 |
| License         | MIT                                                          |

2022-12-09 11:13 UTC, coldic3 approved these changes

2022-12-09 14:47 UTC, mbabker requested changes
This should make use of the `firewall_context_name` config node in the ShopBundle's config instead of continuing to hardcode the firewall name.  This would ensure that the listener is correctly attached to whatever firewall is configured as the shop (frontend) firewall, regardless of name.  Looking at the listener's functionality, I would say there are security implications if it isn't registered as expected.

2022-12-09 15:52 UTC, mbabker approved these changes

2022-12-12 11:49 UTC, Rafikooo approved these changes

2022-12-14 09:33 UTC, jakubtobiasz approved these changes

2022-12-15 07:45 UTC, GSadee approved these changes

2022-12-15 07:45 UTC, merged

2022-12-15 07:45 UTC, GSadee commented
Thank you, Jan! :tada: