ApiBundle fixes in composer.js
Sylius/Sylius pull request #14698
Opened 2023-01-11 10:33 UTC by dawkaa

Give exceptions, such as could not find a driver when commands create a test database. So I added the requirement in composer.js to fix it.

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13

2023-01-12 07:58 UTC, jakubtobiasz requested changes
Also rebase on top of current 1.13 branch as we fixed the root of problem with failing tests.

2023-01-12 07:58 UTC, jakubtobiasz commented on src/Sylius/Bundle/ApiBundle/composer.json
> +        "ext-sqlite3": "*"
Keep alphabetical order please :).

2023-01-13 03:46 UTC, dawkaa commented on src/Sylius/Bundle/ApiBundle/composer.json
> +        "ext-sqlite3": "*"
yes i see

2023-01-13 04:07 UTC, dawkaa commented
i rebased and pushed

2023-01-16 07:27 UTC, jakubtobiasz approved these changes

2023-01-23 15:08 UTC, merged

2023-01-23 15:08 UTC, jakubtobiasz commented
Thanks, @dawkaa! :tada:

2023-01-24 10:41 UTC, dawkaa commented
> 

😁😁