[Documentation][Shop] How to develop a marketplace using Sylius?
Sylius/Sylius pull request #14765
Opened 2023-01-27 15:19 UTC by bitbager

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | N/A                     |
| License         | MIT                                                          |

2023-02-03 13:01 UTC, CoderMaggie commented on docs/cookbook/shop/open-marketplace.rst
> +in the digital space.
```suggestion
A multi-vendor marketplace is a system that enables multiple vendors to sell their products
or services through a centralized website or application. This system facilitates the e-commerce
process by allowing vendors to register, create and manage their own storefronts, list products,
set prices, and receive payments, while the marketplace owner manages the platform and handles
customer service, security, and other related functions. Multi-vendor marketplaces often include 
inventory management, order tracking, and analytics features. This type of platform is commonly used for businesses of
all sizes and industries, particularly those wanting to expand their reach and increase sales and position
in the digital space.
```

2023-02-03 13:01 UTC, CoderMaggie commented on docs/cookbook/shop/open-marketplace.rst
> +with it. What is more, the project is free and distributed under MIT license.
```suggestion
Since Sylius is rather an eCommerce framework than a platform,
it could be easily adjusted to different business models. One of the trending ones
in recent years is a Multi-Vendor Marketplace. `BitBag <https://bitbag.io>`_, our
leading project implementation partner built a product on top of Sylius that
transforms it into a marketplace. It is fully compatible with Symfony and Sylius
meaning you can use all Sylius knowledge, plugins, and Symfony bundles while working
with it. Moreover, the project is free and distributed under an MIT license.
```

2023-02-03 13:01 UTC, CoderMaggie commented on docs/cookbook/shop/open-marketplace.rst
> +* Creating, managing and accepting listings process
```suggestion
* Creating, managing, and accepting listings process
```

2023-02-03 13:01 UTC, CoderMaggie commented on docs/cookbook/shop/open-marketplace.rst
> +The project features:
```suggestion
The project's features:
```

2023-02-03 13:01 UTC, CoderMaggie commented on docs/cookbook/shop/open-marketplace.rst
> +also a possibility to access different panels such as:
```suggestion
The demo can be accessed under `this link <https://demo.open-marketplace.io/>`_. There is
also a possibility to access different panels such as:
```

2023-02-07 11:33 UTC, CoderMaggie commented
The commits need to be squashed 👀

2023-02-08 10:23 UTC, CoderMaggie approved these changes, later dismissed

2023-02-08 10:57 UTC, CoderMaggie commented
After a discussion with the Core Team, I am closing this PR. Open Marketplace is a separate project, it cannot be installed in existing Sylius shops as a plugin/extension in a straightforward way. Due to that it is also not featured within Sylius Store and shouldn't be described within Sylius documentation.

2023-02-09 11:33 UTC, bitbager commented
Judging by the number of likes, I feel like the core team is happy about it not being merged. Thanks for your support and true community spirit. Btw, there is a lot of content describing how to use paid Sylius-related services, which you have no problem storing in docs. What we have done is a free, open-source project based on the vendor that is trending in the eCommerce niche. That is just not fair.

2023-02-09 13:09 UTC, vvasiloi commented
@bitbager I know it feels unfair. I was at first advocating for the merge and pointed out myself to the other examples of 3rd party solutions in the docs, including BitBag's CMS Plugin and Platform.sh. However, my colleagues pointed out some technical aspects of the OM that we don't want to promote. If you manage to make the installation start with a `composer require` instead of a `composer create-project`, then we might reconsider.
For context, the debate started by questioning wherever we should have ANY 3rd party solutions in our docs at all and then slowly calmed down into "we will decide case-by-case".
I hope that makes the situation a bit clearer.

2023-02-09 13:31 UTC, jakubtobiasz commented
I'm not a part of the core team, but I was opt in for closing this PR, so I'll let myself add my 3 cents.

## 1. Architecture problems
Current architecture makes OM not “for Sylius”, but “on Sylius”. You force it (at least in docs) as a standalone solution (because of `create-project`). It is totally useless for current users of Sylius, and makes it harder for future ones. They have to decide whether they want to go with Sylius or OM because at the end of they're two alternative solutions.

## 2. Risk of similar PRs
After merging this PR, anybody made other plugins might come and want to have their page in the docs. We can't (or we shouldn't) keep in the docs 3 different CMS, 2 MVM, etc.

## 3. Bootstrap theme example
Not so long ago, we had to deal with outdated Bootstrap theme doc page, despite it isn't a part of Sylius organization.

## 4. Changing the policy how to deal with 3rd party documentations.
We aren't certain how we deal with 3rd party docs. My opinion – every interested in 3rd party vendor should maintain their docs, and the plugin's page in the store should be the only space to place links to it.

We chose not to merge it (and eventually remove other 3rd parties from our docs). Sylius' docs should be and (after clean up) should stay Sylius (Core)-oriented. It's nothing personal, so far we just haven't had to deal with such PRs.

2023-10-15 10:58 UTC, bitbager commented
Since all the mentioned tech aspects were solved in the project, I am reopening this PR for further discussion.

2023-10-15 19:07 UTC, diimpp requested changes

2023-10-15 19:07 UTC, diimpp commented on docs/cookbook/shop/open-marketplace.rst
> +* `Vendor/shop user <https://demo.open-marketplace.io/en_US/login>`_: `camille@example.com@example.com: password`
It probably meant to be like so
```suggestion
* `Vendor/shop user <https://demo.open-marketplace.io/en_US/login>`_: `camille@example.com: password`
```

2023-10-15 19:07 UTC, diimpp commented on docs/cookbook/index.rst
> +
Please remove trailing empty line

2025-09-09 11:54 UTC, TheMilek commented
Hi!

I'm closing this PR, as it is quite outdated since that time 😅

2025-09-09 11:54 UTC, closed without merging