Allow ProductAttributeValueNormalizer to return a null value
Sylius/Sylius pull request #14788
Opened 2023-02-02 13:50 UTC by vasilvestre

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                  |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | fixes #14748                      |
| License         | MIT                                                          |

2023-02-02 14:38 UTC, jakubtobiasz commented
Hi! Thanks for your contribution @vasilvestre!

Is it possible to cover this change in the spec `src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php`? Thanks in advance!

2023-02-02 15:34 UTC, vasilvestre commented
I'm not really sure my changes are good.. I'm not an expert with spec. Maybe a standalone test case would be better ?

2023-02-02 16:40 UTC, loic425 requested changes

2023-02-02 16:40 UTC, loic425 commented on src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php
> +                    'fr_FR' => null
I do not agree, the value should not exist here, not having a null.

2023-02-02 16:41 UTC, loic425 requested changes

2023-02-02 16:42 UTC, loic425 commented on src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php
> +                    'fr_FR' => null
To be sure, you have to run the new phpspec test before the change on the normalizer itself :D

2023-02-02 16:45 UTC, loic425 commented on src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php
> +                    'fr_FR' => null
Lol I test it locally only with your Phpspec change and the test pass, so that proves nothing :dagger:

2023-02-02 17:11 UTC, loic425 commented on src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductAttributeValueNormalizerSpec.php
> +                    'fr_FR' => null
@jakubtobiasz I've investigated and the bug has been introduced on switch change to map function.

2023-02-03 06:58 UTC, GSadee commented
I'm closing this PR in favour of #14789

2023-02-03 06:58 UTC, closed without merging