There's no canton in Belgium, it's provinces
Sylius/Sylius pull request #14870
Opened 2023-03-21 09:07 UTC by alexandre-castelain

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12               |
| Bug fix?        | no                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets |                      |
| License         | MIT                                                          |

https://en.wikipedia.org/wiki/Provinces_of_Belgium

Maybe we should remove this exemple totally, because it's already the correct name for the provinces.

2023-03-21 11:47 UTC, jakubtobiasz requested changes
Hi 🙋🏼‍♂️!
Thanks for opening PR, but the information about Belgium becomes obsolete in this context :).

2023-03-21 11:47 UTC, jakubtobiasz commented on docs/book/customers/addresses/countries.rst
> +Therefore we understand provinces as states of the USA, voivodeships of Poland, provinces of Belgium or Bundesländer of Germany.
```suggestion
Therefore we understand provinces as states of the USA, voivodeships of Poland or Bundesländer of Germany.
```

2023-03-21 13:07 UTC, alexandre-castelain commented on docs/book/customers/addresses/countries.rst
> +Therefore we understand provinces as states of the USA, voivodeships of Poland, provinces of Belgium or Bundesländer of Germany.
Yeah, that's what I thought ! :)

2023-03-22 05:44 UTC, jakubtobiasz approved these changes

2023-03-22 05:46 UTC, merged

2023-03-22 05:46 UTC, jakubtobiasz commented
Thank you, @alexandre-castelain!