Cover Api steps in paying offline during checkout as guest scenario
Sylius/Sylius pull request #14960
Opened 2023-04-20 13:42 UTC by TheMilek

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                       |
| License         | MIT                                                          |

2023-04-20 14:41 UTC, NoResponseMate approved these changes

2023-04-20 14:49 UTC, jakubtobiasz requested changes

2023-04-20 14:49 UTC, jakubtobiasz commented on features/checkout/paying_for_order/paying_offline_during_checkout_as_guest.feature
> +        Then I should see the thank you page in "French (France)"
When we use `@api @no-ui` I'd like to not use incorrect steps like "I should see the thank you page" as there's no such thing in API.

Making scenarios logically correct > making scenarios passing

2023-04-21 06:56 UTC, jakubtobiasz approved these changes

2023-04-21 09:10 UTC, merged

2023-04-21 09:10 UTC, jakubtobiasz commented
Thank you, @TheMilek!