Cover viewing product associations via API
Sylius/Sylius pull request #15028
Opened 2023-05-11 12:55 UTC by TheMilek

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                       |
| New feature?    | slighly                                                     |
| BC breaks?      | no                                                      |
| Deprecations?   | no  |
| License         | MIT                                                          |

2023-05-11 21:09 UTC, Rafikooo requested changes

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +    }
```suggestion
    public function iShouldSeeTheProductAssociationWithProductsAnd(string $productAssociationName, ProductInterface ...$products): void
    {
        Assert::true($this->isProductAssociationWithProductsAvailable($productAssociationName, $products));
    }
```

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +    public function iShouldNotSeeTheProductAssociationWithProducts(string $productAssociationName): void
```suggestion
    public function iShouldNotSeeTheProductAssociation(string $productAssociationName): void
```

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +            }
I wonder if this "if" is needed
```suggestion
            $associationTypeIri = $this->responseChecker->getValue($associationResponse, 'type');
            $associationTypeResponse = $this->client->showByIri($associationTypeIri);

            $associationNames[] = $this->responseChecker->getValue($associationTypeResponse, 'name');
```

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +        Assert::false(in_array($productAssociationName, $associationNames));
Instead of storing `$associationNames` we could `Assert:notSame` for each of them, but I'm ok with that too

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/EnabledProductInProductAssociationItemExtension.php
> +        private ChannelContextInterface $channelContext,
I'm not sure if this is also the case, but [here](https://github.com/Sylius/Sylius/pull/15023/files#diff-8959ea496540a9ab65c3bee64c4e431703e5d512068389bab567f3524dae9cccL41-R59) we got rid of the channel context in favor of `$context[ContextKeys::CHANNEL]`

2023-05-11 21:09 UTC, Rafikooo commented on src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/EnabledProductInProductAssociationItemExtensionSpec.php
> +        ChannelContextInterface $channelContext,
Arguments should first be ordered as in the constructor
```suggestion
        ChannelContextInterface $channelContext,
        UserContextInterface $userContext,
        UserInterface $user,
        QueryBuilder $queryBuilder,
        QueryNameGeneratorInterface $queryNameGenerator,
```

2023-05-17 05:50 UTC, TheMilek commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +            }
There is a problem when association is not found, the `Expected 'type' not found.` occurs becouse of `$associationTypeIri = $this->responseChecker->getValue($associationResponse, 'type');` line here

2023-05-17 10:01 UTC, NoResponseMate commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +    public function iShouldNotSeeTheProductAssociation(string $productAssociationName): void
Couldn't you just grab the association from a transformer context, generate its IRI and check whether it's included in the product associations?

2023-05-17 10:01 UTC, NoResponseMate commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/EnabledProductInProductAssociationItemExtension.php
> +        if ($user !== null && in_array('ROLE_API_ACCESS', $user->getRoles(), true)) {
Wouldn't it be easier to check if the user implements `AdminUserInterface`?

2023-05-18 11:58 UTC, Rafikooo approved these changes, later dismissed

2023-05-18 12:17 UTC, NoResponseMate commented on src/Sylius/Behat/Context/Api/Shop/ProductContext.php
> +                Assert::notSame($associationTypeIri, $this->iriConverter->getIriFromItem($productAssociationType));
```suggestion
                Assert::notSame($associationTypeIri, $productAssociationTypeIri);
```
Move the iri conversion before the foreach

2023-05-18 12:43 UTC, GSadee approved these changes

2023-05-18 12:43 UTC, GSadee commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/EnabledProductInProductAssociationItemExtension.php
> +        $channel = $queryNameGenerator->generateParameterName('channel');
```suggestion
        $enabledParameterName = $queryNameGenerator->generateParameterName('enabled');
        $channelParameterName = $queryNameGenerator->generateParameterName('channel');
```

2023-05-19 05:13 UTC, merged

2023-05-19 05:13 UTC, GSadee commented
Thanks, Kamil! :1st_place_medal: