Add OrderShipping Symfony Workflow configuration
Sylius/Sylius pull request #15362
Opened 2023-09-25 12:56 UTC by TheMilek

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                   |
| New feature?    | yes                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| License         | MIT                                                          |

2023-09-26 01:18 UTC, diimpp requested changes

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
> +    - { resource: "@SyliusCoreBundle/Resources/config/app/workflows.yml" }
```suggestion
    - { resource: "@SyliusCoreBundle/Resources/config/app/workflows.yaml" }
```

Newer files already use `yaml`, so no reason to fallback to `yml`

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +        ->supports([Order::class])
Does it work fine with extended resource class?

Is it possible or needed to specify `%sylius.model.order.class%` over here instead?

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +        ->initialMarking(['cart']);
```suggestion
        ->initialMarking([OrderShippingStates::STATE_CART]);
```

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +    $orderShipping->place()->name(Sylius\Component\Core\OrderShippingStates::STATE_CART);
I'm not familiar with php configs, but is to possible to add `use` for OrderShippingStates?

```suggestion
    $orderShipping->place()->name(OrderShippingStates::STATE_CART);
```

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +    $orderShipping = $framework->workflows()->workflows('sylius_order_shipping');
```suggestion
    $orderShipping = $framework->workflows()->workflows(OrderShippingTransitions::GRAPH);
```

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +        ->from(Sylius\Component\Core\OrderShippingStates::STATE_READY)
Workflow docs for php config example uses array as values for `from`/`to`

![image](https://github.com/Sylius/Sylius/assets/870747/ae80e265-1df7-49c4-93c5-6ece1be27c1a)

So I think we should follow example for a uniformity

This part too 
```php
->initialMarking(['cart']);
```

WDYT?

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflows.xml
> + (c) Paweł Jędrzejewski
```suggestion
 (c) Sylius Sp. z o.o.
```

Banner missing empty lines
![image](https://github.com/Sylius/Sylius/assets/870747/527d2e3d-e95f-48da-975c-1dce0a9e62d0)

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflows/callbacks/order_shipping_callback.xml
> + This file is part of the Sylius package.
Same

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflows/listeners/order_shipping_listener.xml
> +<!--
Same

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/OrderShippingWorkflowTest.php
> +    public function availableTransitionsForReadyStatus(): iterable
```suggestion
    public function availableTransitionsFromReadyState(): iterable
```

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Workflow/Listener/OrderShipping/AfterOrderShippedListener.php
> +    public function call(Event $event): void
```suggestion
    public function call(CompletedEvent $event): void
```
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Workflow/Event/CompletedEvent.php

2023-09-26 01:18 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Workflow/Listener/OrderShipping/AfterOrderShippedListener.php
I've a concern about this naming scheme,

1. `CoreBundle/Workflow` sounds like I should expect symfony-level code in here, with symfony/workflow extension or classes replacement, not a userland code. (I don't have alternative atm)
2. `CoreBundle/Workflow/Listener` -- `symfony/workflow` uses regular `@event_dispatcher`, regular symfony events -- there is no reason to single workflow listener in special directory. (As far as I see)  `CoreBundle\EventListener\Workflow\**` or `CoreBundle\EventListener\Order\ResolveOrderStateListener`
3. `CoreBundle\Workflow\Callback` -- With `symfony/workflow` we no longer have `callblack` namespace and I don't think, that we should revive it, especially that it's unrelated to workflow in any way. One of the alternatives is to make `CoreBundle\Event\OrderShippingShipped` and just dispatch it.

@Sylius/core-team what do you think?

2023-09-26 11:28 UTC, jakubtobiasz requested changes
We'll stop using Winzou probably in `2.0` or `3.0` so let's stay as close to Symfony workflow as we can.

2023-09-26 11:28 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
Let's stay with YAMLs for now.

2023-09-26 11:28 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflows/callbacks/order_shipping_callback.xml
It could be `callbacks.xml` (or `callback.xml` depending how the other files are named).

2023-09-26 11:28 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflows/listeners/order_shipping_listener.xml
It could be `listeners.xml` (or `listener.xml` depending how the other files are named).

2023-09-26 11:28 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/OrderShippingWorkflowTest.php
<...>/StateMachine/WorkflowAdapter/OrderShippingTest.php 🤔

2023-09-26 11:28 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Workflow/Listener/OrderShipping/AfterOrderShippedListener.php
I vote for `EventListener/Workflow` without splitting on callbacks and guards.

2023-09-26 13:20 UTC, TheMilek commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.php
> +        ->supports([Order::class])
I couldn't find the way to use parameter, but instead I'm gonna use interface 🤔

2023-09-27 07:51 UTC, Wojdylak submitted a review, later dismissed

2023-09-27 08:17 UTC, Rafikooo submitted a review, later dismissed

2023-09-27 10:28 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflow.xml
> +
```suggestion
    <imports>
        <import resource="workflow/*.xml" />
    </imports>
</container>
```

2023-09-27 10:28 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflow/listeners.xml
> +            <argument type="tagged_iterator" tag="sylius.workflow.callback.after_shipped_order" />
As we mentioned in the internal discussion, there is not much value in the additional abstraction for defining callbacks. Let's stay as close as possible to the implementation proposed by Symfony and use for now only Workflow events.

2023-09-27 13:11 UTC, jakubtobiasz approved these changes, later dismissed

2023-09-27 13:11 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.yaml
> +                - Sylius\Component\Core\Model\OrderInterface
`state` field is available in the `\Sylius\Component\Order\Model\OrderInterface` so we can use it.

2023-09-27 14:35 UTC, TheMilek commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.yaml
> +                - Sylius\Component\Core\Model\OrderInterface
there are some methods missing that are doing some mess in OrderShippingStateResolver, im after staying with the one from core for now

2023-09-28 05:19 UTC, GSadee approved these changes

2023-09-28 05:19 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/EventListener/Workflow/OrderShipping/AfterOrderShippedListener.php
> +        $order = $event->getSubject();
```suggestion
        $order = $event->getSubject();
        Assert::isInstanceOf($order, OrderInterface::class);
```

2023-09-28 05:19 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/app/workflow/sylius_order_shipping.yaml
> +                property: ShippingState
```suggestion
                property: shippingState
```

2023-09-28 05:19 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Tests/Functional/StateMachine/WorkflowAdapter/OrderShippingWorkflowTest.php
> +     */
```suggestion
    /** @test */
```

2023-09-28 05:19 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/spec/EventListener/Workflow/OrderShipping/AfterOrderShippedListenerSpec.php
> +        $this->shouldThrow(\InvalidArgumentException::class)->during('onOrderShippingCompleted', [new CompletedEvent($callback->getWrappedObject(), new Marking())]);
```suggestion
        $this
            ->shouldThrow(\InvalidArgumentException::class)
            ->during('onOrderShippingCompleted', [new CompletedEvent($callback->getWrappedObject(), new Marking())])
        ;
```

2023-09-28 05:19 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/spec/EventListener/Workflow/OrderShipping/AfterOrderShippedListenerSpec.php
> +    function it_resolves_orders_after_order_being_shipped(
```suggestion
    function it_resolves_order_state_after_order_being_shipped(
```

2023-09-28 05:21 UTC, merged

2023-09-28 05:21 UTC, GSadee commented
Thanks, Kamil! :tada:

2023-09-28 19:23 UTC, diimpp reviewed
@TheMilek @GSadee workflow's listener file placement is critical to fix

2023-09-28 19:23 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflow.xml
> +
Unnecessary empty line

2023-09-28 19:23 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/workflow/listeners.xml
Either this listener needs to be put at `services/listeners.xml` or new directory `services/listeners/workflow.xml`