[Maintenance] Remove leftover deprecations
Sylius/Sylius pull request #15386
Opened 2023-09-29 15:12 UTC by NoResponseMate

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 2.0 |
| Bug fix?        | no                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | -                      |
| License         | MIT                                                          |

Most likely not the last PR regarding this as more deprecations will come to 1.13

2023-12-01 12:37 UTC, vvasiloi requested changes

2023-12-01 12:37 UTC, vvasiloi commented on src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneChoiceType.php
> -            trigger_deprecation(
This one should be converted to an exception now to require passing scope types.

2023-12-01 12:37 UTC, vvasiloi commented on src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
> +        private ?ExpiredCartsRemoverInterface $expiredCartsRemover,
```suggestion
        private ExpiredCartsRemoverInterface $expiredCartsRemover,
```

2023-12-01 14:43 UTC, vvasiloi approved these changes, later dismissed

2023-12-07 08:44 UTC, jakubtobiasz approved these changes

2023-12-07 08:45 UTC, merged