Updated links that were redirecting to 404
Sylius/Sylius pull request #15408
Opened 2023-10-05 19:32 UTC by benbd5

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                    |
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets |                      |
| License         | MIT                                                          |

Updated links that were redirecting to 404 like : https://docs.sylius.com/book/orders/payments

2023-10-06 22:56 UTC, diimpp requested changes
Hi @benbd5, please remove `.zshrc` file and changes should be good to be merged :+1:

2023-10-06 22:56 UTC, diimpp commented on .zshrc
Please remove this file

2023-10-09 07:09 UTC, benbd5 commented on .zshrc
It's done

2023-10-12 02:23 UTC, diimpp approved these changes

2023-10-12 07:39 UTC, NoResponseMate approved these changes

2023-10-12 12:10 UTC, GSadee approved these changes

2023-10-12 12:11 UTC, merged

2023-10-12 12:11 UTC, GSadee commented
Thank you, Benjamin! :tada: