Refresh payments when skipped payment step and the payment method is already disabled
Sylius/Sylius pull request #15455
Opened 2023-10-19 20:16 UTC by senghe

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #11678                      |
| License         | MIT                                                          |

2023-10-19 20:18 UTC, senghe commented
Hi all, I've fixed the issue mentioned in the table by refreshing (removing and recreating) payments, when at least one of current payment has disabled method. I wrote only specs for this, as the issue seems to be a bit complex for behats I think.

2023-10-24 11:52 UTC, SzymonFilipek commented
/bns:start

2023-10-24 11:59 UTC, SzymonFilipek commented
/bns:deploy

2023-10-24 12:04 UTC, SzymonFilipek commented
/bns:start

2023-10-25 09:51 UTC, SzymonFilipek commented
/bns:start

2023-10-25 13:42 UTC, SzymonFilipek submitted a review, later dismissed
Changes passed QA check

2023-12-01 12:11 UTC, vvasiloi requested changes
Hey @senghe, thanks for your contribution!
I left some feedback on the code changes.
My primary concern is wherever this issue is also reproduced after checkout and if we can solve both of them in one shot.
I believe we could also cover this with some Behat tests, let me know if you need help with that.

2023-12-01 12:11 UTC, vvasiloi commented on src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
> +        private OrderPaymentRefresherInterface $orderPaymentsRefresher,
This has to be done similarly to how the order payments remover was introduced, meaning the constructor argument has to be appended and made optional.

2023-12-01 12:11 UTC, vvasiloi commented on src/Sylius/Component/Core/Payment/Refresher/OrderPaymentRefresher.php
> +    }
This should only apply to payments with `cart` state.
Also, as a personal code taste, I would do an early return if `$channel->isSkippingPaymentStepAllowed()` is `false` and replace the loop by calling the `exists` method on the collection with a closure.
```suggestion
    public function isPaymentRefreshingNeeded(OrderInterface $order): bool
    {
        $channel = $order->getChannel();

        if (null !== $channel && !$channel->isSkippingPaymentStepAllowed()) {
            return false;
        }

        return $order->getPayments()->exists(static function (int $key, PaymentInterface $payment): bool {
            return $payment->getState() === PaymentInterface::STATE_CART
                && $payment->getMethod() !== null
                && !$payment->getMethod()->isEnabled();
        });
    }
```

2023-12-01 12:11 UTC, vvasiloi commented on src/Sylius/Component/Core/Payment/Refresher/OrderPaymentRefresher.php
> +    }
For now, I would only refresh `cart` payments and when that works then see if the same issue applies to `new` payments and fix that too.

```suggestion
    public function refreshPayments(OrderInterface $order, string $targetState): void
    {
        if ($targetState !== PaymentInterface::STATE_CART) {
            return;
        }

        $this->orderPaymentsRemover->removePayments($order);

        try {
            $newPayment = $this->orderPaymentProvider->provideOrderPayment($order, $targetState);
            $order->addPayment($newPayment);
        } catch (NotProvidedOrderPaymentException) {
            return;
        }
    }
```

2023-12-01 12:11 UTC, vvasiloi commented on src/Sylius/Component/Core/Payment/Refresher/OrderPaymentRefresher.php
> +use Webmozart\Assert\Assert;
A lot of these imports are not used.

2023-12-01 12:11 UTC, vvasiloi commented on src/Sylius/Component/Core/Payment/Refresher/OrderPaymentRefresherInterface.php
> +use Webmozart\Assert\Assert;
Most of these imports are not used.

2026-04-08 12:47 UTC, TheMilek commented
I'm closing this PR in favor of new one to supported version https://github.com/Sylius/Sylius/pull/18965

2026-04-08 12:47 UTC, closed without merging