[API] Change interface of decorated IriConverter
Sylius/Sylius pull request #15644
Opened 2023-12-15 14:17 UTC by GSadee

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | api-platform-3|
| Bug fix?        | yes                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| Related tickets | |
| License         | MIT                                                          |

2023-12-18 04:03 UTC, diimpp requested changes

2023-12-18 04:03 UTC, diimpp commented on src/Sylius/Behat/Resources/config/suites.yml
> -<<<<<<< HEAD
Please remove

2024-01-06 16:19 UTC, diimpp approved these changes

2024-04-03 14:00 UTC, GSadee commented
Closing in favour of #16089

2024-04-03 14:00 UTC, closed without merging