[API] Finish covering managing orders
Sylius/Sylius pull request #15660
Opened 2023-12-18 14:41 UTC by TheMilek

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                     |
| New feature?    | yes                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| License         | MIT                                                          |

2023-12-19 07:53 UTC, Wojdylak commented on features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
> +    Scenario: Accessing payment's order from the payments resource
Could you connect these scenarios?
```
        Then I should see order "#00000001" with details
```

2023-12-19 07:53 UTC, Wojdylak commented on features/shipping/managing_shipments/accessing_shipments_order_from_shipment_index.feature
> +    Scenario: Accessing shipment's order from the shipments resource
Could you connect these scenarios?

2023-12-19 07:53 UTC, Wojdylak commented on src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
> +    public function itShouldHaveOrderShippingState(string $orderShippingState): void
The scenario and function names are not consistent.

2023-12-19 07:53 UTC, Wojdylak commented on src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
> +    public function iShouldSeeOrderPageWithDetailsOfOrder(OrderInterface $order): void
```suggestion
    public function iShouldSeeOrder(OrderInterface $order): void
```

2023-12-19 07:53 UTC, Wojdylak commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryExtension/OrderExtension.php
> +        if ($user instanceof AdminUserInterface && in_array('ROLE_API_ACCESS', $user->getRoles(), true)) {
Could we use  `SectionProviderInterface` here and check only if it is `AdminApiSection`?

2023-12-19 16:02 UTC, jakubtobiasz requested changes

2023-12-19 16:02 UTC, jakubtobiasz commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryExtension/OrderExtension.php
> +        $this->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);
It looks wierd as hell. It'd be better to write a private method with logic from the `applyToCollection` and invoke it in both `applyToCollection` and `applyToItem` methods.

2023-12-19 16:02 UTC, jakubtobiasz commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryExtension/OrderExtension.php
> +        if ($this->sectionProvider->getSection() instanceof AdminApiSection) {
You can use early return here. 

```
if (!$this->sectionProvider->getSection() instanceof AdminApiSection) {
    return;
}

// rest of the code
```

2023-12-20 09:04 UTC, NoResponseMate requested changes

2023-12-20 09:04 UTC, NoResponseMate commented on features/order/managing_orders/order_details/being_unable_to_see_cart.feature
>      Scenario: Seeing basic information about an order
```suggestion
    Scenario: Being unable to see the details of a cart
```

2023-12-20 09:04 UTC, NoResponseMate commented on features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
> +        Then I should see order "#00000001" with details
```suggestion
        Then I should see the details of order "#00000001"
```

2023-12-20 09:04 UTC, NoResponseMate commented on features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
> +    Scenario: Accessing payment's order from the payments resource
```suggestion
    Scenario: Accessing payment's order from the payment
```
or just
```suggestion
    Scenario: Accessing the order of a payment
```
similar w/ shipments

2023-12-20 09:04 UTC, NoResponseMate commented on src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
> +        $this->sharedStorage->get('order')->getShipments()->first()->setTracking($trackingCode);
No. Use the API.

2023-12-20 09:04 UTC, NoResponseMate commented on tests/Api/Admin/OrdersTest.php
> +            'order/fulfilled_order.yaml',
```suggestion
            'order/fulfilled.yaml',
```

2023-12-20 09:23 UTC, TheMilek commented on src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
> +        $this->sharedStorage->get('order')->getShipments()->first()->setTracking($trackingCode);
forgive me, totally forgot to change it XD

2023-12-20 11:19 UTC, NoResponseMate commented on src/Sylius/Bundle/ApiBundle/Doctrine/QueryExtension/OrderExtension.php
> +            ->andWhere(sprintf('%s.state != :%s', $rootAlias, $stateParameter))
Won't this fail if we pass more than one state?

2023-12-20 11:19 UTC, NoResponseMate commented on src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
> +        );
The formatting here is weird, but let's leave it for the ecs build to take care of.

2023-12-20 11:19 UTC, NoResponseMate commented on src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
> +            </argument>
Might be worth to parametrize this

2023-12-20 15:10 UTC, NoResponseMate approved these changes

2023-12-20 18:05 UTC, jakubtobiasz approved these changes

2023-12-20 18:05 UTC, merged

2023-12-20 18:05 UTC, jakubtobiasz commented
Thank you, @TheMilek!