Validate resending order confirmation email
Sylius/Sylius pull request #15735
Opened 2024-01-16 12:06 UTC by TheMilek

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | no                                                       |
| New feature?    | yes                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| License         | MIT                                                          |

Continuation of https://github.com/Sylius/Sylius/pull/15712 with validation added

2024-01-17 07:57 UTC, Wojdylak approved these changes, later dismissed

2024-01-17 07:57 UTC, Wojdylak commented on src/Sylius/Bundle/OrderBundle/Resources/config/app/config.yml
> +parameters:
This is just a suggestion: the parameters before the jms_serializer.

2024-02-01 13:33 UTC, Wojdylak submitted a review, later dismissed

2024-02-01 15:21 UTC, Rafikooo submitted a review, later dismissed

2024-02-02 14:10 UTC, jakubtobiasz requested changes

2024-02-02 14:10 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Validator/Constraints/ResendOrderConfirmationEmailWithValidOrderStateValidator.php
> +        }
It's not covered in the PHPSpec from what I see.

2024-02-02 14:10 UTC, jakubtobiasz commented on src/Sylius/Bundle/CoreBundle/Validator/Constraints/ResendOrderConfirmationEmailWithValidOrderStateValidator.php
> +        }
As above + this layer shouldn't be aware about the "Http". Especially this exception is "general". Try to use (or create) meaningful exceptions telling what really went wrong. Here you might create (if it doesn't exist yet) the `OrderNotFoundException`.

2024-02-02 16:50 UTC, jakubtobiasz approved these changes

2024-02-02 16:52 UTC, merged

2024-02-02 16:52 UTC, jakubtobiasz commented
Thank you, @TheMilek!