[API] Administrator and Customer endpoints Reorganization
Sylius/Sylius pull request #15949
Opened 2024-03-05 21:05 UTC by Rafikooo

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | a bit                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| License         | MIT                                                          |

In this PR, we grouped administrator and customer-related endpoints with their respective tags.

<img width="890" alt="image" src="https://github.com/Sylius/Sylius/assets/40125720/7bc82ace-9d63-430b-b2ea-86dce6882c46">

<img width="804" alt="image" src="https://github.com/Sylius/Sylius/assets/40125720/754d072b-6de1-4cae-8d85-2d1bb78b1f31">

2024-03-06 11:50 UTC, Wojdylak commented
It's good to have these endpoints in two palce. Additionally, I would suggest changing the paths as follows:
`admin/authentication-token` => `admin/administrators/login` or `admin/administrators/token`
`admin/reset-password-requests` => `admin/administrators/reset-password`
`shop/account-verification-requests` => `shop/customers/verification`
`shop/authentication-token` => `shop/customers/login` or `shop/customers/token`
`shop/reset-password-requests` => `shop/customers/reset-password`

I'm not sure if the Customer group is the right place for the `shop/contact-requests` endpoint.

2024-03-07 07:42 UTC, jakubtobiasz commented
> I'm not sure if the Customer group is the right place for the shop/contact-requests endpoint.

We can add it to the channel, as you contact with the people handling the concrete channel.

2024-03-07 07:43 UTC, jakubtobiasz submitted a review, later dismissed

2024-03-08 16:18 UTC, NoResponseMate approved these changes, later dismissed

2024-03-08 16:18 UTC, NoResponseMate commented on src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerVerification.xml
> +                <attribute name="path">/customers/verification</attribute>
```suggestion
                <attribute name="path">/customers/verify</attribute>
```
Wdyt? IMO it's more in line with the other actions' naming

2024-03-11 09:15 UTC, jakubtobiasz requested changes, later dismissed
Everything seems fine for me 👌🏻. However, we should update the UPGRADE file in the same PR, to avoid missing information about changed endpoints, what is pretty important.

2024-03-11 09:33 UTC, Wojdylak approved these changes, later dismissed

2024-03-11 09:33 UTC, Wojdylak commented on src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
> +        private readonly string $resource,
I am uncertain about the `resource` variable. My suggestion is to leave as it was and pass the`admin/administrator` or `shop/customer` value to the `section` variable. WDYT?

2024-03-12 07:53 UTC, Wojdylak approved these changes, later dismissed

2024-03-12 09:16 UTC, Rafikooo commented on templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig
> +        waitForElement('#operations-tag-Security', adjustDOMWhenReady);
First, I attempted to override the JS section that handles resource generation, but since I couldn't achieve that, I resorted to DOM manipulation. I hope this solution suffices for our needs.

2024-03-12 10:36 UTC, NoResponseMate commented on UPGRADE-API-1.13.md
> +    * `PATCH` `/shop/reset-password-requests/{resetPasswordToken}` -> `PATCH` `/shop/customers/reset-password/{token}`
```suggestion
    * `POST` `/admin/reset-password-requests` -> `POST` `/admin/administrators/reset-password`
    * `PATCH` `/admin/reset-password-requests/{resetPasswordToken}` -> `PATCH` `/admin/administrators/reset-password/{token}`
    * `POST` `/shop/reset-password-requests` -> `POST` `/shop/customers/reset-password`
    * `PATCH` `/shop/reset-password-requests/{resetPasswordToken}` -> `PATCH` `/shop/customers/reset-password/{token}`
```
To me grouping by context is more natural

2024-03-12 10:36 UTC, NoResponseMate commented on templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig
> +                console.log(tokenRequestContainer);
```suggestion
```

2024-03-12 15:18 UTC, NoResponseMate approved these changes

2024-03-12 15:20 UTC, merged

2024-03-12 15:20 UTC, NoResponseMate commented
Thank you, @Rafikooo!