Styles for thank-you page after registration
Sylius/Sylius pull request #16470
Opened 2024-06-26 12:36 UTC by bartek-sek

![image](https://github.com/Sylius/Sylius/assets/129760562/fe362d4a-2dd8-4628-8a06-e5e7dfd2806d)

2024-06-26 13:25 UTC, kulczy requested changes

2024-06-26 13:25 UTC, kulczy commented on src/Sylius/Bundle/ShopBundle/Resources/views/Account/register/registerThankYou.html.twig
title doesn't match convention

2024-06-27 09:29 UTC, bartek-sek commented on src/Sylius/Bundle/ShopBundle/Resources/views/Account/register/registerThankYou.html.twig
Fixed

2024-06-27 12:22 UTC, merged

2024-06-27 12:23 UTC, kulczy commented
thanks @bartek-sek 🤛