Edit sections unify
Sylius/Sylius pull request #16568
Opened 2024-07-11 16:09 UTC by kulczy

First of all:
- changing the naming of the section from `Details` to `General`
- if there is only one section on a subpage, it remains without a header
- adding headers to `Translations` sections
- moved `code` field to be always first
- shipping method folder structure unified

2024-07-12 07:41 UTC, Wojdylak approved these changes, later dismissed

2024-07-12 07:41 UTC, Wojdylak commented on src/Sylius/Bundle/AdminBundle/templates/customer_group/form/sections/general.html.twig
> +                {{ 'sylius.ui.general'|trans }}
```suggestion

```
There is only one section here

2024-07-15 18:14 UTC, CoderMaggie submitted a review, later dismissed

2024-07-18 05:08 UTC, GSadee reviewed
Adjust also Exchange Rate hooks and templates, and the rebase is necessary 😅

2024-07-18 05:08 UTC, GSadee commented on src/Sylius/Bundle/AdminBundle/templates/customer/form/sections/general.html.twig
Shouldn't the header here also be `General` instead of `Customer details`? 🤔

2024-07-22 09:30 UTC, mpysiak approved these changes

2024-07-22 09:54 UTC, mpysiak requested changes, later dismissed
There are some 500 errors in tests

2024-07-24 11:50 UTC, Wojdylak approved these changes

2024-07-24 11:52 UTC, merged