Organization of Commands/Messages
Sylius/Sylius pull request #16642
Opened 2024-07-29 06:45 UTC by Wojdylak

| Q               | A
|-----------------|-----
| Branch?         | 2.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | #15730
| License         | MIT

2024-08-01 07:24 UTC, NoResponseMate commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/command_handler.xml
> +        <service id="Sylius\Bundle\CoreBundle\CommandHandler\Admin\Account\RequestResetPasswordEmailHandler">
Maybe change the service ids to dotted notation here as well?

2024-08-01 17:07 UTC, diimpp requested changes, later dismissed
Request changes is due comment

2024-08-01 17:07 UTC, diimpp commented on src/Sylius/Bundle/AdminBundle/Tests/DependencyInjection/Compiler/BackwardsCompatibility/ReplaceEmailManagersPassTest.php
Would you need to update definitions
```
       $this->setDefinition(ResendShipmentConfirmationEmailDispatcher::class, new Definition());
```
to named service usage as in 
```php
        $this->setDefinition('sylius.email_manager.shipment', new Definition());
```
since services ids updated to named ones.
![image](https://github.com/user-attachments/assets/e0d33742-db62-456c-81e6-3d65c8668f6b)

2024-08-01 17:07 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/spec/CommandHandler/Admin/Account/SendResetPasswordEmailHandlerSpec.php
> +use Sylius\Bundle\CoreBundle\Command\Admin\Account\SendResetPasswordEmail;
Uses should be sorted differently for this case, maybe it's true for others as well, would be cool to apply CS checks.

```patch
--- use Sylius\Bundle\CoreBundle\Mailer\ResetPasswordEmailManagerInterface;
use Sylius\Bundle\CoreBundle\Command\Admin\Account\SendResetPasswordEmail;
+++ use Sylius\Bundle\CoreBundle\Mailer\ResetPasswordEmailManagerInterface;
```

2024-08-01 17:07 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Resources/config/serialization/Messages/Admin/Account/ResetPassword.xml
This namespace should follow regular php namespacing, so `Command` and not `Messages`.

```patch
--- src/Sylius/Bundle/CoreBundle/Resources/config/serialization/Messages/Admin/Account/ResetPassword.xml
+++ src/Sylius/Bundle/CoreBundle/Resources/config/serialization/Command/Admin/Account/ResetPassword.xml
```

2024-08-02 07:17 UTC, Wojdylak commented on src/Sylius/Bundle/AdminBundle/Tests/DependencyInjection/Compiler/BackwardsCompatibility/ReplaceEmailManagersPassTest.php
The `ReplaceEmailManagersPass` class was added to maintain backward compatibility, so I think it will be removed in 2.0 version.

2024-08-02 13:05 UTC, diimpp commented on src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
```patch
--- <parameter key="sylius.message.admin_user_create.validation_groups" type="collection">
+++ <parameter key="sylius_admin.console.command.create_admin_user.validation_groups" type="collection">
```
Not sure about `<parameter>sylius_user_create</parameter>` validation group if it needs to be changed to anything.

```patch
--- <argument>%sylius.message.admin_user_create.validation_groups%</argument>
+++ <argument>%sylius_admin.console.command.create_admin_user.validation_groups%</argument>
```

2024-08-02 13:24 UTC, diimpp commented on src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
Sorry, wrong IDs, here correct ones

```patch
--- <parameter key="sylius.message.admin_user_create.validation_groups" type="collection">
+++ <parameter key="sylius_admin.command_handler.create_admin_user.validation_groups" type="collection">
```

```patch
--- <argument>%sylius.message.admin_user_create.validation_groups%</argument>
+++ <argument>%sylius_admin.command_handler.create_admin_user.validation_groups%</argument>
```

2024-08-05 09:44 UTC, GSadee approved these changes

2024-08-05 09:44 UTC, GSadee commented on src/Sylius/Bundle/CoreBundle/Resources/config/services/command_dispatcher.xml
> +        <service id="sylius.command_dispatcher.resend_order_confirmation_email" class="Sylius\Bundle\CoreBundle\CommandDispatcher\ResendOrderConfirmationEmailDispatcher">
I wonder if it would not be good to introduce these new ids already in version 1.14, and here just remove the deprecated (old) ones 🤔

2024-08-05 10:02 UTC, merged