Enable tests for placing orders as impersonated shop users and for picking up cart created in UI in the api
Sylius/Sylius pull request #17035
Opened 2024-09-26 13:13 UTC by Wojdylak

| Q               | A
|-----------------|-----
| Branch?         | 2.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | n/a
| License         | MIT

2024-09-27 06:29 UTC, GSadee requested changes, later dismissed

2024-09-27 06:29 UTC, GSadee commented on .github/workflows/ci_e2e-custom.yaml
> +                run: vendor/bin/behat --colors --strict --no-interaction -vvv -f progress --tags="~@javascript&&~@mink:chromedriver&&~@todo&&~@cli" --suite-tags="@api,@domain,@hybrid" || vendor/bin/b
We should not add it as we have suite-tags set here properly and we do not want to skip over the scenarios that should be executed here

2024-09-27 13:17 UTC, NoResponseMate approved these changes

2024-09-30 04:21 UTC, mpysiak approved these changes

2024-09-30 05:18 UTC, GSadee approved these changes

2024-09-30 05:18 UTC, merged