[Zone] Added priority property
Sylius/Sylius pull request #17191
Opened 2024-10-10 14:31 UTC by JakobTolkemit

| Q               | A
|-----------------|-----
| Branch?         | 1.14 
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no 
| Related tickets | none
| License         | MIT

The PR https://github.com/Sylius/Sylius/pull/15275 broke the tax calculation in our shop. The reason being that the `ZoneMatcher` now returns the first matching zone, while previously it was the last.

2024-10-30 10:02 UTC, mamazu commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +        $this->addSql('ALTER TABLE sylius_zone ADD priority INT NOT NULL');
```suggestion
        $this->addSql('ALTER TABLE sylius_zone ADD priority INT NOT NULL DEFAULT 0');
        $this->addSql('UPDATE sylius_zone SET priority = id');
```

2024-10-30 10:04 UTC, mamazu commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +        $this->addSql('ALTER TABLE sylius_zone ADD priority INT NOT NULL');
By default the priority should be the same as the Id.

2024-11-14 22:21 UTC, diimpp requested changes
Hi,

I've no comments on feature necessity, but please bear in mind, that new features are usually added to a next release, which is 2.0 in the current situation.

As for "priority" implementation, please follow existing example of `position` field with gedmo sortable. We cannot affort two different implementation for the same problem.

Please take a look at [payment methods](https://demo.sylius.com/admin/payment-methods/)

![image](https://github.com/user-attachments/assets/9ee7f8c5-103f-4456-81e5-8b60419befd0)

2024-11-14 22:21 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> + */
```suggestion
```

2024-11-14 22:21 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +        // this up() migration is auto-generated, please modify it to your needs
```suggestion
```

2024-11-14 22:21 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +        return '';
Please add description in same style as for other CoreBundle migrations.

2024-11-14 22:21 UTC, diimpp commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +        // this down() migration is auto-generated, please modify it to your needs
```suggestion
```

2024-11-14 22:21 UTC, diimpp commented on src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml
> +        <field name="priority" column="priority" type="integer"/>
Field should be managed by gedmo sortable

2024-11-15 08:26 UTC, Prometee requested changes

2024-11-15 08:26 UTC, Prometee commented on src/Sylius/Bundle/CoreBundle/Migrations/Version20241010135921.php
> +final class Version20241010135921 extends AbstractMigration
If it's MySQL extends the Sylius Mysql Abstract Migration class and don't forget to also generate PostgreSQL.

2024-11-26 10:23 UTC, mamazu commented
@diimpp Thanks for the review. Let me give you some context why this is needed. Let me give you some context.

## The problem
In 1.13 there were some changes to optimize zone matching. Before it would loop over all the entries and return the last zone matching the address and now it returns the first one (because it's a database query now).

This is not a problem for most users. However in our case we've set up zones from smallest to widest. So something like this: 
1st zone: World wide (0% taxes)
2nd zone: Europe
1st zone: Germany (19% taxes)

Which in the old model would return the last matching zone "Germany" however now it would return the zone worldwide. The general problem is that if you have overlapping zones in Sylius there is no way to set in what order they match.

## The solution(s)
I've brought this issue up with the Sylius team and offered two solutions. Either validate that zones are not overlapping (that's hard to do with performance in mind) or configure in what order zones are being matched (this PR).

If you have any other ideas on how to solve this better feel free to let us know.

2025-09-17 08:52 UTC, Rafikooo commented
I’m closing this ticket in favor of https://github.com/Sylius/Sylius/pull/18374

2025-09-17 08:52 UTC, closed without merging