performance, accessibility, best practices and seo improvements
Sylius/Sylius pull request #17496
Opened 2024-11-20 23:19 UTC by damonsson

| Q               | A
|-----------------|-----
| Branch?         | 2.0 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

2024-11-21 09:20 UTC, GSadee submitted a review, later dismissed

2024-11-21 09:20 UTC, GSadee commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base/footer/content/payment_methods.html.twig
> +        <a class="link-reset" href="https://x.com/Sylius" aria-label="x logo">{{ ux_icon('tabler:brand-x', { class: 'icon icon-md' }) }}</a>
```suggestion
        <a class="link-reset" href="https://www.instagram.com/sylius.team/" target="_blank" aria-label="instagram logo">{{ ux_icon('tabler:brand-instagram', { class: 'icon icon-md' }) }}</a>
        <a class="link-reset" href="https://www.facebook.com/SyliusEcommerce/" target="_blank" aria-label="facebook logo">{{ ux_icon('tabler:brand-facebook', { class: 'icon icon-md' }) }}</a>
        <a class="link-reset" href="https://x.com/Sylius" target="_blank" aria-label="x logo">{{ ux_icon('tabler:brand-x', { class: 'icon icon-md' }) }}</a>
```
What do you think?

2024-11-21 11:14 UTC, kulczy requested changes

2024-11-21 11:14 UTC, kulczy commented on src/Sylius/Bundle/ShopBundle/templates/shared/components/main_image.html.twig
> +<img {{ attributes.defaults({ class: 'img-fluid' }) }} src="{{ path }}" {{ sylius_test_html_attribute('main-image') }} alt="Product {{ product.name }} picture" />
this should be translatable

2024-11-21 11:14 UTC, kulczy commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +        <meta name="description" content="Explore the Sylius demo – a flexible e-commerce platform built on Symfony. Discover features to customize your online store and test its capabilities!"/>
this should be translatable

2024-11-21 15:37 UTC, gitrequests commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +        <meta name="description" content="Explore the Sylius demo – a flexible e-commerce platform built on Symfony. Discover features to customize your online store and test its capabilities!"/>
> this should be translatable

Sylius currently has a problem with SEO. Meta tags are not present on any page (description, keywords)... But, as far as I understand, work is underway in this direction. The basic template has a block `metatags` and a twig hook (which is not currently used).
https://github.com/Sylius/Sylius/blob/4f8ae56b40d1789f1234d20b4bdc6a595af23bea/src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig#L15-L17

Perhaps you need a plugin for SEO)

2024-11-22 15:29 UTC, damonsson commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +        <meta name="description" content="Explore the Sylius demo – a flexible e-commerce platform built on Symfony. Discover features to customize your online store and test its capabilities!"/>
This piece of code is meant to be just a placeholder in the repository for when someone sets up a demo.

2024-11-22 15:41 UTC, kulczy approved these changes

2024-11-23 00:06 UTC, merged

2024-11-23 14:07 UTC, gitrequests commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +            <meta name="description" content="{{ 'sylius.meta_description'|trans }}"/>
I don't think this is a very good idea. If the Sylius team or community finally decides to write a plugin that will set meta tags for all pages using a hook (on next line), this line will cause a problem. And anyway, this is a basic template, it will set this meta tag on all pages of the site. Google will be shocked)

2024-11-23 14:07 UTC, gitrequests commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +            <meta name="description" content="{{ 'sylius.meta_description'|trans }}"/>
Right now, the problem of one tag on a page can be solved on a specific project very simply.

Create a file: `templates/bundles/SyliusShopBundle/homepage/index.html.twig`
```twig
{% set homepage_hook = 'sylius_shop.homepage.index' %}
{% set prefixes = [homepage_hook] %}

{% extends '@SyliusShop/shared/layout/base.html.twig' %}

{% block metatags %}
    {{ parent() }}
    <meta name="description" content="{{ sylius.channel.description }}">
{% endblock %}

{% block content %}
    {% hook homepage_hook %}
{% endblock %}
```

This will immediately insert the meta description tag with the content from the store settings.

---

But it seems to me that this complex problem with meta tags should be solved somehow. The funniest thing is that everything for this already exists! For example, the meta description and meta keyword fields are already in the product model, but they are not displayed on the product page. 🤷‍♂️

2024-11-24 17:01 UTC, damonsson commented on src/Sylius/Bundle/ShopBundle/templates/shared/layout/base.html.twig
> +            <meta name="description" content="{{ 'sylius.meta_description'|trans }}"/>
You're absolutely right, I didn't think this through. I'll revert this change in the next PR. Thank you so much for catching that!