SYL-4224: UI improvements
Sylius/Sylius pull request #17597
Opened 2024-12-31 11:45 UTC by bartek-sek

### Taxon tree check/uncheck buttons:
**Before**
![image](https://github.com/user-attachments/assets/72e8c4c8-1de0-4a18-adda-fbd45a85390f)
**After**
![image](https://github.com/user-attachments/assets/b64f093f-a104-44e4-bf08-f4335394a0ea)

### Mobile product accordions paddings:
**Before**
![image](https://github.com/user-attachments/assets/145b7fc5-844d-4b2d-87ec-efd5129f083b)
**After**
![image](https://github.com/user-attachments/assets/ab52b0d3-e8d3-475e-8725-eb106c63f158)

### Date formats
Changed date format to d-m-Y as it is in other  and disabled text wrapping.

**Before**
![image](https://github.com/user-attachments/assets/4cf8b3ab-0834-40a5-b625-735cdb8e3a13)
**After**
![image](https://github.com/user-attachments/assets/e6692f88-7e15-4262-86b1-71a5c5929090)

2025-01-09 06:09 UTC, mpysiak approved these changes, later dismissed

2025-01-10 05:58 UTC, GSadee commented on features/admin/promotion/managing_catalog_promotions/browsing_catalog_promotions.feature
> +        And the catalog promotion "Winter sale" operates between "10-11-2021 13:45" and "08-01-2022 23:59"
This change caused the tests for this scenario to not pass, you can revert this to an earlier version, this format has nothing to do with how we show it on the grid

2025-01-10 11:10 UTC, Prometee requested changes, later dismissed

2025-01-10 11:10 UTC, Prometee commented on src/Sylius/Bundle/AdminBundle/templates/catalog_promotion/grid/field/date.html.twig
>          <div>{{ data|date('H:i') }}</div>
```suggestion
        <div class="text-nowrap">{{ data|format_date }}</div>
        <div>{{ data|format_time }}</div>
```

Dates, times, currencies, locales display are different for each admin user locale.

2025-01-10 11:10 UTC, Prometee commented on src/Sylius/Bundle/AdminBundle/templates/shared/grid/field/date.html.twig
>          <div>{{ data|date('H:i:s') }}</div>
```suggestion
        <div class="text-nowrap">{{ data|format_date}}</div>
        <div>{{ data|format_time }}</div>
```

2025-01-11 08:12 UTC, loic425 commented on src/Sylius/Bundle/AdminBundle/templates/catalog_promotion/grid/field/date.html.twig
>          <div>{{ data|date('H:i') }}</div>
Yes I agree we could pass the format as field option with a default on the template

2025-01-11 08:27 UTC, loic425 commented on src/Sylius/Bundle/AdminBundle/templates/catalog_promotion/grid/field/date.html.twig
>          <div>{{ data|date('H:i') }}</div>
But with date_format and time_format vars I think.

2025-01-13 12:15 UTC, GSadee approved these changes

2025-01-13 12:25 UTC, GSadee commented on src/Sylius/Bundle/AdminBundle/templates/catalog_promotion/grid/field/date.html.twig
>          <div>{{ data|date('H:i') }}</div>
We will change this format and make it consistent in the entire Admin in a separate PR, so this part has been reverted from this PR

2025-01-13 12:26 UTC, merged